### ISSUE TITLE
Master branch: Segmentation fault at startup

### ISSUE THREAD

**Issue by psilhavy** [LMMS/lmms#1329]
linux 3.17.3 glibc-2.20 gcc 4.9.2
```
Program received signal SIGSEGV, Segmentation fault.
0xb7fe7286 in elf_machine_rel (reloc=0xb02a2bfc, skip_ifunc=<optimized out>, 
    reloc_addr_arg=<optimized out>, version=<optimized out>, sym=0xb02a23a0, 
    map=0x8433078) at ../sysdeps/i386/dl-machine.h:338
338           struct link_map *sym_map = RESOLVE_MAP (&sym, version, r_type);
(gdb) bt
#0  0xb7fe7286 in elf_machine_rel (reloc=0xb02a2bfc, 
    skip_ifunc=<optimized out>, reloc_addr_arg=<optimized out>, 
    version=<optimized out>, sym=0xb02a23a0, map=0x8433078)
    at ../sysdeps/i386/dl-machine.h:338
#1  elf_dynamic_do_Rel (skip_ifunc=<optimized out>, lazy=<optimized out>, 
    nrelative=<optimized out>, relsize=<optimized out>, 
    reladdr=<optimized out>, map=<optimized out>) at do-rel.h:137
#2  _dl_relocate_object (scope=0x844c8f0, reloc_mode=0, consider_profiling=0)
    at dl-reloc.c:264
#3  0xb7feef21 in dl_open_worker (a=0xbfffebcc) at dl-open.c:416
#4  0xb7feab05 in _dl_catch_error (objname=objname@entry=0xbfffebc4, 
    errstring=errstring@entry=0xbfffebc8, 
    mallocedp=mallocedp@entry=0xbfffebc3, operate=0xb7feebd0 <dl_open_worker>, 
    args=0xbfffebcc) at dl-error.c:187
#5  0xb7fee669 in _dl_open (file=0xb7ffdeb0 "/usr/lib/libasound.so.2", 
    mode=-2147483646, caller_dlopen=0xb70a0002 <snd_dlopen+285>, 
    nsid=<optimized out>, argc=1, argv=0xbffff234, env=0xbffff23c)
    at dl-open.c:650
#6  0xb64d6c85 in dlopen_doit (a=0xbfffed80) at dlopen.c:66
#7  0xb7feab05 in _dl_catch_error (objname=0x833ae6c, errstring=0x833ae70, 
    mallocedp=0x833ae68, operate=0xb64d6c10 <dlopen_doit>, args=0xbfffed80)
    at dl-error.c:187
#8  0xb64d7331 in _dlerror_run (
---Type <return> to continue, or q <return> to quit---
    operate=operate@entry=0xb64d6c10 <dlopen_doit>, args=args@entry=0xbfffed80)
    at dlerror.c:163
#9  0xb64d6d2e in __dlopen (file=0xb7ffdeb0 "/usr/lib/libasound.so.2", mode=2)
    at dlopen.c:87
#10 0xb70a0002 in snd_dlopen () from /usr/lib/libasound.so.2
#11 0xb7098ec1 in snd_config_hooks_call () from /usr/lib/libasound.so.2
#12 0xb7099166 in snd_config_hooks () from /usr/lib/libasound.so.2
#13 0xb709a22c in snd_config_update_r () from /usr/lib/libasound.so.2
#14 0xb709a2b5 in snd_config_update () from /usr/lib/libasound.so.2
#15 0xb70be2fe in snd_pcm_open () from /usr/lib/libasound.so.2
#16 0x080f8473 in AudioAlsa::AudioAlsa (this=0x8439350, 
    _success_ful=@0xbffff013: false, _mixer=0x849c700)
    at /usr/src/lmms/src/core/audio/AudioAlsa.cpp:55
#17 0x08125ee7 in Mixer::tryAudioDevices (this=0x849c700)
    at /usr/src/lmms/src/core/Mixer.cpp:745
#18 0x08126d6a in Mixer::initDevices (this=0x849c700)
    at /usr/src/lmms/src/core/Mixer.cpp:195
#19 0x0813c8da in engine::init (_has_gui=true)
    at /usr/src/lmms/src/core/engine.cpp:91
#20 0x080b5748 in main (argc=1, argv=0xbffff234)
    at /usr/src/lmms/src/core/main.cpp:440
(gdb) 
```

**Comment by psilhavy** [comment]
Since version 1.1.0 ( branch stable-1.1,  last commit 62df7688961bac6892e82e8ba609ded058a75bc6)  bug disappears .

**Comment by tresf** [comment]
:+1:
