### ISSUE TITLE
Turning "Tension" knob in automation editor before selecting an automation causes segfault

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2327]
**Steps to reproduce**:
1. Open lmms and hit F8 to bring up the automation editor (the automation editor should have text saying "Please open an automation pattern with the context menu of a control!")
2. Turn the "Tension" knob in the window's menu bar.

LMMS segfaults with the following stack trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004f5a1f in AutomationPattern::setTension (this=0x0, _new_tension=...) at /home/colin/src/lmms/src/core/AutomationPattern.cpp:166
166			m_tension = _new_tension.toFloat();
(gdb) bt
#0  0x00000000004f5a1f in AutomationPattern::setTension (this=0x0, _new_tension=...) at /home/colin/src/lmms/src/core/AutomationPattern.cpp:166
#1  0x00000000005e0a78 in AutomationEditor::setTension (this=0x1a4eaa0) at /home/colin/src/lmms/src/gui/editors/AutomationEditor.cpp:1679
#2  0x000000000064aa4d in AutomationEditor::qt_static_metacall (_o=0x1a4eaa0, _c=QMetaObject::InvokeMetaMethod, _id=12, _a=0x7fffffffd550)
    at /home/colin/src/lmms/build/debug/src/moc_AutomationEditor.cpp:172
#3  0x00007ffff4c74fea in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#4  0x0000000000654b85 in Model::dataChanged (this=0x7fffe6c97ce0) at /home/colin/src/lmms/build/debug/src/moc_Model.cpp:145
#5  0x00000000004f118b in AutomatableModel::setValue (this=0x7fffe6c97ce0, value=0.98816669)
    at /home/colin/src/lmms/src/core/AutomatableModel.cpp:233
#6  0x000000000061e9c0 in Knob::setPosition (this=0x1a5adf0, _p=...) at /home/colin/src/lmms/src/gui/widgets/Knob.cpp:708
#7  0x000000000061e29e in Knob::mouseMoveEvent (this=0x1a5adf0, _me=0x7fffffffdb00) at /home/colin/src/lmms/src/gui/widgets/Knob.cpp:587
#8  0x00007ffff74c8f08 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff748600c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff748bbe9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff4c4689b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff748aaf2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff74e374b in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff74e5cfb in ?? () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff748600c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff748b4e6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff4c4689b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff51a5c81 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#19 0x00007ffff51a7955 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#20 0x00007ffff518ce08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#21 0x00007fffe65329f0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#22 0x00007ffff385b9fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff385bce0 in ?? () from /usr/lib/libglib-2.0.so.0
#24 0x00007ffff385bd8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#25 0x00007ffff4c9d23f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff4c4426a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff4c4c20c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#28 0x00000000004eee22 in main (argc=1, argv=0x7fffffffe7c8) at /home/colin/src/lmms/src/core/main.cpp:677
```

A fix should be as simple as adding something like `if (m_pattern != NULL)` at the appropriate place.

**Comment by michaelgregorius** [comment]
Please see pull request #2328 for a fix of the crash and the addition of a missing update when patterns are changed.
