### ISSUE TITLE
Project Won't Open

### ISSUE THREAD

**Issue by GlitchMasterCubed** [LMMS/lmms#2395]
The project I had just finished won't open. It is a different opening error from the other errors that I have seen, LMMS doesn't even load any plugins before crashing. Is the project too big perhaps? I just had added about 5 total plugins to my mastering chain for the final export.

![error](https://cloud.githubusercontent.com/assets/10779691/10213300/0fd2e48e-67c0-11e5-9ec9-03543b6a7221.PNG)

**Comment by musikBear** [comment]
This resource is not the right forum for Q&A, Q&A should takes place in our dedicated help-forum :)
Could i ask you to create an account there: http://lmms.io/forum/ ? 
You need to include:
* OS (+service-pack-ver)
* lmms vers
* hardware specification (ram & soundcard is the most imortant)
* lmms sound device chosen
* if any -screenshots of error
* if relevant, demo mmp
* names and best download links of the failing vst's

**Comment by M374LX** [comment]
If a (probably corrupted) project file causes LMMS to crash and no error message is shown, I suppose we have a bug.

**Comment by grejppi** [comment]
@GlitchMasterCubed, could you post the project file in question, and/or find a way to reproduce this issue? Is it a VST plugin that is causing this; if so, which one?

**Comment by GlitchMasterCubed** [comment]
Thanks for the replies. I am using Windows 10 with the most recent updates as of now, LMMS 1.1.3, laptop model: MSI GE62 2QE, SDL sound device, there isn't an error message it just crashes when I try to load the project, I don't think that it's any of my VSTs (just in case you want to know I was using Synth1, Ambience reverb, reaeq, Sidewidener, Grancomp 3, and EaReckon Analog87 EQ. I haven't had any problems with these plugins in the past.) I was also using a lot of automation (8+ tracks).

Here is the project in question (yes, I named it untitled):
https://www.dropbox.com/s/3bruxp2rjtlrh3m/Untitled.mmpz?dl=0
https://www.dropbox.com/s/ogg4ncjkial2ev8/Untitled.mmpz.bak?dl=0

**Comment by grejppi** [comment]
The VST support layer is a very delicate part of LMMS.

I can't see anything wrong with the project file, but when I try to open it LMMS freezes too when it's loading effects in the mixer.

Now, I don't even have any of the plugins used in this project, but LMMS spawns the VST host process anyway, and gets stuck trying to reach it.

The symptoms look very much like #1875, so closing as a duplicate. Feel free to continue the discussion there.

```
(gdb) bt
#0  0x00007ffff7bcb23d in recvmsg () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fffefee19b7 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fffefee2198 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff2271db8 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff2271efe in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff22721dd in _XEventsQueued ()
    at /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff2264207 in XPending () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007fffe5e5ecfe in  () at /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#8  0x00007ffff39413fd in g_main_context_prepare (context=context@entry=0x9632d0, priority=priority@entry=0x7fffffffc260)
    at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3410
#9  0x00007ffff3941de8 in g_main_context_iterate (context=context@entry=0x9632d0, block=block@entry=0, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3788
#10 0x00007ffff3941fcc in g_main_context_iteration (context=0x9632d0, may_block=0) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3869
#11 0x00007ffff693f85e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#12 0x00007ffff7131c66 in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007ffff691401d in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#14 0x000000000053e699 in RemotePluginBase::waitForMessage(RemotePluginBase::mes---Type <return> to continue, or q <return> to quit---
sage const&, bool) (this=0x1790c90, _wm=..., _busy_waiting=true)
    at ../include/RemotePlugin.h:950
#15 0x000000000054074a in RemotePlugin::waitForInitDone(bool) (this=0x1790c90, _busyWaiting=true) at ../include/RemotePlugin.h:690
#16 0x00007fff77eaadf3 in VstPlugin::tryLoad(QString const&) (this=0x1790c60, remoteVstPluginExecutable=...) at ../plugins/vst_base/VstPlugin.cpp:183
#17 0x00007fff77eaa8bb in VstPlugin::VstPlugin(QString const&) (this=0x1790c60, _plugin=...) at ../plugins/vst_base/VstPlugin.cpp:102
#18 0x00007fff77c8da56 in VstEffect::openPlugin(QString const&) (this=0x7fffea4844e0, _plugin=...) at ../plugins/VstEffect/VstEffect.cpp:132
#19 0x00007fff77c8d364 in VstEffect::VstEffect(Model*, Plugin::Descriptor::SubPluginFeatures::Key const*) (this=0x7fffea4844e0, _parent=0xceb4d0, _key=0x7fffffffc920) at ../plugins/VstEffect/VstEffect.cpp:65
#20 0x00007fff77c8dd5c in lmms_plugin_main(Model*, void*) (_parent=0xceb4d0, _data=0x7fffffffc920) at ../plugins/VstEffect/VstEffect.cpp:178
#21 0x000000000053658e in Plugin::instantiate(QString const&, Model*, void*) (pluginName=..., parent=0xceb4d0, data=0x7fffffffc920)
    at ../src/core/Plugin.cpp:125
#22 0x000000000050006f in Effect::instantiate(QString const&, Model*, Plugin::Descriptor::SubPluginFeatures::Key*) (pluginName=..., _parent=0xceb4d0, _key=0x7fffffffc920) at ../src/core/Effect.cpp:121
#23 0x000000000050123c in EffectChain::loadSettings(QDomElement const&) (this=0xceb4d0, _this=...) at ../src/core/EffectChain.cpp:97
---Type <return> to continue, or q <return> to quit---
#24 0x000000000054977a in SerializingObject::restoreState(QDomElement const&) (this=0xceb4f0, element=...) at ../src/core/SerializingObject.cpp:70
#25 0x000000000050a416 in FxMixer::loadSettings(QDomElement const&) (this=0xd0a780, _this=...) at ../src/core/FxMixer.cpp:734
#26 0x000000000054977a in SerializingObject::restoreState(QDomElement const&) (this=0xd0a7a0, element=...) at ../src/core/SerializingObject.cpp:70
#27 0x000000000051870b in JournallingObject::restoreState(QDomElement const&) (this=0xd0a7a0, _this=...) at ../src/core/JournallingObject.cpp:92
#28 0x000000000054c4a7 in Song::loadProject(QString const&) (this=0xc84ff0, fileName=...) at ../src/core/Song.cpp:983
...
```
