### ISSUE TITLE
Access to Mixer::m_playHandlesToRemove is not properly synchronized

### ISSUE THREAD

**Issue by Fastigium** [LMMS/lmms#2610]
I'm making music with `master` running in gdb to catch stacktraces of crashes, and I just got a SIGSEGV on erasing an element from `m_playHandlesToRemove` in Mixer.cpp. No wonder, since that member is written to in three places ([one](https://github.com/LMMS/lmms/blob/4e30d957010580f01910dace12bcb6d15681dde0/src/core/Mixer.cpp#L372) [two](https://github.com/LMMS/lmms/blob/4e30d957010580f01910dace12bcb6d15681dde0/src/core/Mixer.cpp#L476) [three](https://github.com/LMMS/lmms/blob/4e30d957010580f01910dace12bcb6d15681dde0/src/core/Mixer.cpp#L681)) and none of those use the same lock. I'll fix this later, for now I'll keep hunting for crashes.

For reference, here is the gdb output:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa3f33700 (LWP 24036)]
__memmove_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2969
2969	../sysdeps/x86_64/multiarch/memcpy-ssse3.S: No such file or directory.
(gdb) bt
#0  __memmove_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2969
#1  0x00007ffff687776a in QListData::remove(int) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff6877a39 in QListData::erase(void**) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x0000000000522fc8 in QList<PlayHandle const*>::erase (this=0xdb3e70, 
    it=...) at /usr/include/qt4/QtCore/qlist.h:466
#4  0x0000000000520083 in Mixer::renderNextBuffer (this=0xdb3de0)
    at /.../lmms/src/core/Mixer.cpp:372
#5  0x0000000000521b9d in Mixer::fifoWriter::run (this=0xf18de0)
    at /.../lmms/src/core/Mixer.cpp:986
#6  0x00007ffff685a32f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff7bc4182 in start_thread (arg=0x7fffa3f33700)
    at pthread_create.c:312
#8  0x00007ffff420e47d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by Fastigium** [comment]
Right, pull request made: #2626. I'd be grateful if anyone could look it over. I'll be testing it myself by making music with it applied as well.

**Comment by Fastigium** [comment]
For the record: I decided to go ahead and merge, as it's a small change and I've tested it myself for numerous hours without crashes or deadlocks.
