### ISSUE TITLE
LMMS is kicked by JACK when exporting

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#2934]
Freshly compiled master branch, elementary OS Freya

```
Version 1.1.90-gfa19f00 (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)
```

Steps to reproduce:
1. Load the `Skiessi - Onion` demo project.
2. Press the export button
3. An error message about LMMS getting kicked by jack appeares: 
   ![screenshot from 2016-07-24 01 42 09](https://cloud.githubusercontent.com/assets/6282045/17080843/e7c097a6-513f-11e6-8083-7430c1b3ea8e.png)
4. When you click the export button, it gets to around 8% and then it crashes.

Backtrace: 

```
(gdb) r
Starting program: /home/umcaruje/github/lmms/build/lmms 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Gtk-Message: Failed to load module "pantheon-filechooser-module"
[New Thread 0x7fffdefaa700 (LWP 5789)]
[New Thread 0x7fffde7a9700 (LWP 5790)]
[New Thread 0x7fffddfa8700 (LWP 5791)]
[New Thread 0x7fffdd7a7700 (LWP 5792)]
[Thread 0x7fffdd7a7700 (LWP 5792) exited]
[New Thread 0x7fffdd7a7700 (LWP 5794)]
[New Thread 0x7fffc76e2700 (LWP 5795)]
[New Thread 0x7fffc6ee1700 (LWP 5796)]
VST sync support disabled in your configuration
[New Thread 0x7fffdc0bd700 (LWP 5797)]
[New Thread 0x7fffbc1e2700 (LWP 5798)]
[New Thread 0x7fff864e4700 (LWP 5799)]
[New Thread 0x7fff85ce3700 (LWP 5800)]
[New Thread 0x7fffbc161700 (LWP 5801)]
[Thread 0x7fffddfa8700 (LWP 5791) exited]
[New Thread 0x7fffddfa8700 (LWP 5809)]
SuspendRefNum error
JackClient::Execute error name = lmms
[Thread 0x7fffbc161700 (LWP 5801) exited]
[New Thread 0x7fff84946700 (LWP 5810)]
Jack server was closed but clients are still allocated, cleanup...
Cleanup client ref = 6
Server is not running
[Thread 0x7fffbc1e2700 (LWP 5798) exited]
[Thread 0x7fffdc0bd700 (LWP 5797) exited]
[New Thread 0x7fffdc0bd700 (LWP 5811)]
[New Thread 0x7fffbc1e2700 (LWP 5812)]
[New Thread 0x7fff85436700 (LWP 5813)]
[Thread 0x7fff85ce3700 (LWP 5800) exited]
[New Thread 0x7fff85ce3700 (LWP 5814)]
MemoryManager: Couldn't find pointer info for pointer: 0x7fffec413420

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff85436700 (LWP 5813)]
0x00007ffff434ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff434ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 5788
        selftid = 5813
#1  0x00007ffff434e028 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fff85435ab0, sa_sigaction = 0x7fff85435ab0}, sa_mask = {__val = {140735429171904, 140735005338040, 
              140737351947559, 140733193388037, 0, 140737328874176, 140737290284336, 3, 140735005338040, 140735429171776, 140737351976149, 1, 2147483648, 
              140737333966784, 10, 140737333966808}}, sa_flags = -2059180288, sa_restorer = 0x30203a7265746e69}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff6852042 in qt_message_output(QtMsgType, char const*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#3  0x00007ffff68523a9 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#4  0x00007ffff6852bb4 in qFatal(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#5  0x00000000004e3a51 in MemoryManager::free(void*) ()
No symbol table info available.
#6  0x00000000004ec351 in NotePlayHandle::done() ()
No symbol table info available.
#7  0x00000000004ec87e in NotePlayHandleManager::release(NotePlayHandle*) ()
No symbol table info available.
#8  0x00000000004e7695 in Mixer::renderNextBuffer() ()
No symbol table info available.
#9  0x000000000051660d in AudioDevice::getNextBuffer(float (*) [2]) ()
No symbol table info available.
#10 0x00000000005182c0 in AudioJack::processCallback(unsigned int, void*) ()
No symbol table info available.
#11 0x00007ffff5dd70ed in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
No symbol table info available.
#12 0x00007ffff5dd67e8 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
No symbol table info available.
#13 0x00007ffff5df2a70 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
No symbol table info available.
#14 0x00007ffff7bc4184 in start_thread (arg=0x7fff85436700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fff85436700
        now = <optimized out>
---Type <return> to continue, or q <return> to quit---
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735429175040, -460631744468812815, 1, 0, 140735429175744, 140735429175040, 460646275460299761, 
                460614725172001777}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#15 0x00007ffff440e37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

```

**Comment by zonkmachine** [comment]
Related #2845 ( crash mentioned )

**Comment by sub26nico** [comment]
Same issue here, distro :Librazik (Debian Jessie audio oriented), with
 Lmms version 1.2.0-rc2 (Linux/i386, Qt 4.8.6, GCC 4.9.2).
Exporting  with Jack crashes Lmms. No problem with Alsa.

**Comment by sub26nico** [comment]
Lmms version  1.1.90+20170508~gitff4ffd1-0librazik1

**Comment by trebmuh** [comment]
...which is package from https://github.com/LMMS/lmms/commit/ff4ffd17f41ffd04ab179492868c40a55c591f35
(I'm the packager)

**Comment by Umcaruje** [comment]
@PhysSong your PR fixes the crash, but I still get the jack is kicked message, though that can be a seperate issue. I also noticed a crash when canceling exporting using any backend, so I think it's not related to your PR.

Good job :+1:

**Comment by PhysSong** [comment]
> I also noticed a crash when canceling exporting using any backend

Does LMMS crash for every project, or some specific projects?

**Comment by PhysSong** [comment]
> but I still get the jack is kicked message

Could you run both jack server and LMMS on terminal and check for their output? It may help fixing the issue.

**Comment by PhysSong** [comment]
> `SuspendRefNum error`

Seems like an timeout error message of JACK2. @Umcaruje Do you use JACK MIDI interface? If so, does changing MIDI interface helps?

**Comment by PhysSong** [comment]
Since the crash seems to be fixed in #4005, I've changed the title. Waiting for informations...

**Comment by trebmuh** [comment]
Is that's still happening with 1.2.1 ? If not, this issue could be closed.

**Comment by PhysSong** [comment]
@Umcaruje Waiting for your response...
