### ISSUE TITLE
Crash: called Track::getTCO( 0 ), but TCO 0 doesn't exist

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2963]
Version 1.1.90- 54a9aa6 (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)
Also tested at version: 7e99b1504f702a9895d1676668141fbac34b7ad7

Program sometimes freezes on drag-drop while playing. I've only seen this with BBTracks.
Loop a BBTrack, drag-drop sound clips and/or presets and sooner or later it'll hang with the cursor still being a hand symbol with a plus sign. Samples may be a bit more sensitive than presets.

I believe this may be related to #2693 and also #2957 .

Backtrace while dropping a snare:
[backtrace full](https://gist.github.com/zonkmachine/1b5fcd7b4250d916c65b9a80214a27a9)

```
(gdb) run
...
[New Thread 0x7fffbe77a700 (LWP 16053)]
[New Thread 0x7fffbdf79700 (LWP 16054)]
called Track::getTCO( 0 ), but TCO 0 doesn't exist
QObject: Cannot create children for a parent that is in a different thread.
(Parent is InstrumentTrack(0x7fffeaf78f60), parent's thread is QThread(0x96ad00), current thread is QThread(0x1039290)
^C
Program received signal SIGINT, Interrupt.
pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff685a816 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x0000000000524696 in Mixer::requestChangeInModel (this=0xbca340) at /home/zonkmachine/builds/lmms/lmms/src/core/Mixer.cpp:762
#3  0x000000000052440e in Mixer::removePlayHandlesOfTypes (this=0xbca340, _track=0x7fffeaf78f60, types=3 '\003')
    at /home/zonkmachine/builds/lmms/lmms/src/core/Mixer.cpp:723
#4  0x000000000060d3a4 in InstrumentTrack::silenceAllNotes (this=0x7fffeaf78f60, removeIPH=true)
    at /home/zonkmachine/builds/lmms/lmms/src/tracks/InstrumentTrack.cpp:437
#5  0x000000000060f01e in InstrumentTrack::loadInstrument (this=0x7fffeaf78f60, _plugin_name=...)
    at /home/zonkmachine/builds/lmms/lmms/src/tracks/InstrumentTrack.cpp:816
#6  0x00000000005b13f2 in TrackContainerView::dropEvent (this=0x1491b30, _de=0x7fffffffbf50)
    at /home/zonkmachine/builds/lmms/lmms/src/gui/TrackContainerView.cpp:389
#7  0x00000000005bec14 in BBTrackContainerView::dropEvent (this=0x1491b30, de=0x7fffffffbf50)
    at /home/zonkmachine/builds/lmms/lmms/src/gui/editors/BBEditor.cpp:261
#8  0x00007ffff712226a in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#9  0x00007ffff70d2e2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007ffff70da326 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007ffff695c4dd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#12 0x00007ffff715b7b1 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007ffff715bb45 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007ffff715cd90 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#15 0x00007ffff695c5b2 in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#16 0x00007ffff70d2db8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007ffff70d95dd in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007ffff695c4dd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#19 0x00007ffff70d8d93 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007ffff714d9eb in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x00007ffff714d289 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#22 0x00007ffff7174b32 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#23 0x00007ffff39c4e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff39c5048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff39c50ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff69897a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#27 0x00007ffff7174be6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#28 0x00007ffff695b0af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#29 0x00007ffff695b3a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#30 0x00007ffff715d0bd in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007ffff70e3f44 in QDrag::start(QFlags<Qt::DropAction>) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#32 0x00000000005ab8d8 in StringPairDrag::StringPairDrag (this=0x2a54b50, _key=..., _value=..., _icon=..., _w=0x10d4490)
    at /home/zonkmachine/builds/lmms/lmms/src/gui/StringPairDrag.cpp:57
#33 0x000000000058424c in FileBrowserTreeWidget::mouseMoveEvent (this=0x10d4490, me=0x7fffffffd540)
    at /home/zonkmachine/builds/lmms/lmms/src/gui/FileBrowser.cpp:470
#34 0x00007ffff7122645 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#35 0x00007ffff74c404e in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#36 0x00007ffff75d3633 in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#37 0x00007ffff7612230 in QTreeView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#38 0x00007ffff695c646 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#39 0x00007ffff70d2e0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#40 0x00007ffff70d95dd in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#41 0x00007ffff695c4dd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#42 0x00007ffff70d8d93 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#43 0x00007ffff714d9eb in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#44 0x00007ffff714d289 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#45 0x00007ffff7174b32 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#46 0x00007ffff39c4e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff39c5048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff39c50ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007ffff69897be in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#50 0x00007ffff7174be6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#51 0x00007ffff695b0af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#52 0x00007ffff695b3a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#53 0x00007ffff6960b79 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#54 0x00000000004dbfc0 in main (argc=1, argv=0x7fffffffe088) at /home/zonkmachine/builds/lmms/lmms/src/core/main.cpp:873
(gdb) 
```

**Comment by zonkmachine** [comment]
This bug was fixed in #2981
