### ISSUE TITLE
Travis-CI Autodeploy Failed

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#3210]
Pinging @Lukas-W as he set it up :)

```
Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: lmms
CPack: - Install project: lmms
CPack: Create package
CPack: - package: /home/travis/build/LMMS/lmms/build/lmms-1.2.0-rc2-win32.exe generated.
dpl.0
Fetching: dpl-1.8.29.gem (100%)
Successfully installed dpl-1.8.29
1 gem installed
dpl.1
Installing deploy dependencies
Fetching: addressable-2.4.0.gem (100%)
Successfully installed addressable-2.4.0
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.2.gem (100%)
Successfully installed faraday-0.9.2
Fetching: sawyer-0.7.0.gem (100%)
Successfully installed sawyer-0.7.0
Fetching: octokit-4.3.0.gem (100%)
Successfully installed octokit-4.3.0
5 gems installed
Fetching: mime-types-2.99.3.gem (100%)
Successfully installed mime-types-2.99.3
1 gem installed
dpl.2
Preparing deploy
Logged in as Lukas W
Deploying to repo: LMMS/lmms
Current tag is: v1.2.0-rc2
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
Saved working directory and index state WIP on (no branch): 43a77a0 Let sample tracks play from any song position (#3133)
HEAD is now at 43a77a0 Let sample tracks play from any song position (#3133)
sh: 0: getcwd() failed: No such file or directory
mv: cannot move ‘/home/travis/dpl’ to ‘.dpl’: No such file or directory
dpl.3
Deploying application
sh: 0: getcwd() failed: No such file or directory
fatal: Unable to read current working directory: No such file or directory
/home/travis/.rvm/gems/ruby-2.2.5/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - lmms-1.2.0-rc2-win32.exe (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/provider/releases.rb:130:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/provider/releases.rb:111:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/provider/releases.rb:102:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/provider/releases.rb:102:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/provider.rb:145:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/provider.rb:145:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.29/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by Umcaruje** [comment]
Tried to patch it with https://github.com/LMMS/lmms/commit/bc0802c8c5406bba2a064749e351a59a69871c24

**Comment by Umcaruje** [comment]
That didn't help, my condition is probably off, I have to sleep now, will look into it tommorow

**Comment by Lukas-W** [comment]
Fixed with 4db1db5ecaa183b24525296e8d344bf789b78f00

**Comment by Umcaruje** [comment]
Awesome work @Lukas-W, may I ask how did you manage to push to an already exisiting tag, I'm curious

**Comment by Lukas-W** [comment]
I deleted the tag remotely first using `git push origin :refs/tags/v1.2.0-rc2`. Then re-created it as usual. Probably not the wisest thing to do, I hope this doesn't cause any problems for devs who already pulled the old `v1.2.0-rc2` tag.
Didn't you do the same? Before I changed it, `v1.2.0-rc2` pointed to your commit bc0802c, but I guess it must have pointed to an older commit before that, namely 43a77a0219fc95fd017ae7af99d98a7cbb04bdd2.

**Comment by tresf** [comment]
> Didn't you do the same? 

Yes, but through web interface. 🙊

**Comment by Lukas-W** [comment]
I couldn't figure out how to remove a tag through the web interface. 😆

**Comment by tresf** [comment]
> I couldn't figure out how to remove a tag through the web interface. 😆

1. Remove release
![image](https://cloud.githubusercontent.com/assets/6345473/21724769/ac4b10e2-d403-11e6-8d8c-1458c07aee96.png)
2. Click on orphaned tag
![image](https://cloud.githubusercontent.com/assets/6345473/21724862/fb0e941a-d403-11e6-80d5-044c1a02dee4.png)
3. Delete tag
![image](https://cloud.githubusercontent.com/assets/6345473/21724891/13530f9c-d404-11e6-8fb2-0e61fa2d37a5.png)

**Comment by Umcaruje** [comment]
@tresf he probably couldn't delete the release because I published it, same as I couldn't delete your release 😃 

@Lukas-W thanks for the explanation, as Tres said, we pretty much did the same, just over the web interface. Yours looked like magic though, because you didn't end up deleting the release, just the tag.

**Comment by Lukas-W** [comment]
I see, got to delete the release first. Thanks @tresf 

> Yours looked like magic though

✨
I did have to re-publish the release on GitHub though.
