### ISSUE TITLE
Project with Sample Track crash on export from command line

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3338]
Projects containing Sample Tracks fails on export from command line since the big update in 43a77a0219fc95fd017ae7af99d98a7cbb04bdd2
@BaraMGB 

```
Loading project...
QObject::connect: Cannot connect (null)::positionMarkerMoved() to SampleTCO::playbackPositionChanged()
Segmentation fault (core dumped)

...

Core was generated by `./lmms -r /home/zonkmachine/lmms/projects/buggar/largeSamples/11min.mmp -o test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000054fb5c in GuiApplication::songEditor (this=0x0) at /home/zonkmachine/builds/lmms/lmms/include/GuiApplication.h:54
54		SongEditorWindow* songEditor() { return m_songEditor; }
(gdb) bt
#0  0x000000000054fb5c in GuiApplication::songEditor (this=0x0) at /home/zonkmachine/builds/lmms/lmms/include/GuiApplication.h:54
#1  0x000000000061fa56 in SampleTCO::SampleTCO (this=0x7f2b2db97ee0, _track=0x7f2b2db97ae0)
    at /home/zonkmachine/builds/lmms/lmms/src/tracks/SampleTrack.cpp:87
#2  0x0000000000622469 in SampleTrack::createTCO (this=0x7f2b2db97ae0) at /home/zonkmachine/builds/lmms/lmms/src/tracks/SampleTrack.cpp:677
#3  0x00000000005590b3 in Track::loadSettings (this=0x7f2b2db97ae0, element=...) at /home/zonkmachine/builds/lmms/lmms/src/core/Track.cpp:2146
#4  0x0000000000549d24 in SerializingObject::restoreState (this=0x7f2b2db97b00, element=...)
    at /home/zonkmachine/builds/lmms/lmms/src/core/SerializingObject.cpp:70
#5  0x000000000051b1b2 in JournallingObject::restoreState (this=0x7f2b2db97b00, _this=...)
    at /home/zonkmachine/builds/lmms/lmms/src/core/JournallingObject.cpp:92
#6  0x000000000055852c in Track::create (element=..., tc=0x274eb40) at /home/zonkmachine/builds/lmms/lmms/src/core/Track.cpp:2009
#7  0x000000000055e2e1 in TrackContainer::loadSettings (this=0x274eb40, _this=...) at /home/zonkmachine/builds/lmms/lmms/src/core/TrackContainer.cpp:123
#8  0x0000000000549d24 in SerializingObject::restoreState (this=0x274eb60, element=...)
    at /home/zonkmachine/builds/lmms/lmms/src/core/SerializingObject.cpp:70
#9  0x000000000051b1b2 in JournallingObject::restoreState (this=0x274eb60, _this=...)
    at /home/zonkmachine/builds/lmms/lmms/src/core/JournallingObject.cpp:92
#10 0x000000000054cb08 in Song::loadProject (this=0x274eb40, fileName=...) at /home/zonkmachine/builds/lmms/lmms/src/core/Song.cpp:1025
#11 0x00000000004dcdcd in main (argc=5, argv=0x7fff01a651b8) at /home/zonkmachine/builds/lmms/lmms/src/core/main.cpp:670
(gdb) 
```

**Comment by BaraMGB** [comment]
Do you have a guess what's going on here?
