### ISSUE TITLE
Delay based effects - occasional crashes on export

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3555]
LMMS sometimes crashes on export when using delay based effects.
This has been seen with: Delay, Flanger , Multitap Echo and ReverbSC  all native effects.

See discussion here https://github.com/LMMS/lmms/pull/3403#issuecomment-285455640

```
Core was generated by `./lmms'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _int_malloc (av=0x7f25d82b6760 <main_arena>, bytes=16) at malloc.c:3389
3389	malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=0x7f25d82b6760 <main_arena>, bytes=16) at malloc.c:3389
#1  0x00007f25d7f7a6c0 in __GI___libc_malloc (bytes=16) at malloc.c:2891
#2  0x00007f25b8547afb in sp_dcblock_create (p=0x7f25ceccad48) at /home/zonkmachine/builds/lmms/lmms/plugins/ReverbSC/dcblock.c:20
#3  0x00007f25b854395b in ReverbSCEffect::changeSampleRate (this=0x7f25cecca420) at /home/zonkmachine/builds/lmms/lmms/plugins/ReverbSC/ReverbSC.cpp:143
#4  0x00007f25b8545db4 in ReverbSCControls::changeSampleRate (this=0x7f25cecca9d8)
    at /home/zonkmachine/builds/lmms/lmms/plugins/ReverbSC/ReverbSCControls.cpp:66
#5  0x00007f25b8547d18 in ReverbSCControls::qt_static_metacall (_o=0x7f25cecca9f8, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7f2578004f70)
    at /home/zonkmachine/builds/lmms/lmms/build/plugins/ReverbSC/moc_ReverbSCControls.cxx:51
```

**Comment by zonkmachine** [comment]
I don't think this is particular for ReverbSC but I've got a similar crash with the lmms Delay (Thread 2 !)


```
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) thread apply all bt

Thread 4 (Thread 0x7fb67296f700 (LWP 1896)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fb681123816 in wait (time=18446744073709551615, this=0x1866990) at thread/qwaitcondition_unix.cpp:86
#2  QWaitCondition::wait (this=<optimized out>, mutex=0x7fb67296ee40, time=18446744073709551615) at thread/qwaitcondition_unix.cpp:158
#3  0x000000000053461e in MixerWorkerThread::run (this=0x1875650) at /home/zonkmachine/builds/lmms/lmms/src/core/MixerWorkerThread.cpp:162

Thread 3 (Thread 0x7fb63f289700 (LWP 1903)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00007fb681121f4a in thread_sleep (ti=ti@entry=0x7fb63f288e00) at thread/qthread_unix.cpp:492
#2  0x00007fb681122805 in QThread::usleep (usecs=<optimized out>) at thread/qthread_unix.cpp:530
#3  0x00000000005315fc in AudioDummy::run (this=0x19b6170) at /home/zonkmachine/builds/lmms/lmms/include/AudioDummy.h:109

Thread 2 (Thread 0x7fb6828897c0 (LWP 1895)):
#0  0x00007fb66a1c2520 in StereoDelay::setSampleRate (this=0x1ac2c30, sampleRate=44100)
    at /home/zonkmachine/builds/lmms/lmms/plugins/Delay/StereoDelay.cpp:87
#1  0x00007fb66a1be604 in DelayEffect::changeSampleRate (this=0x7fb67544ac60) at /home/zonkmachine/builds/lmms/lmms/plugins/Delay/DelayEffect.cpp:150
#2  0x00007fb66a1c0a1e in DelayControls::changeSampleRate (this=0x7fb67544b218) at /home/zonkmachine/builds/lmms/lmms/plugins/Delay/DelayControls.cpp:74

Thread 1 (Thread 0x7fb644d43700 (LWP 1902)):
#0  0x00007fb66a1c23d8 in StereoDelay::tick (this=0x1ac2c30, frame=0x1ab97e8) at /home/zonkmachine/builds/lmms/lmms/plugins/Delay/StereoDelay.cpp:63
#1  0x00007fb66a1be295 in DelayEffect::processAudioBuffer (this=0x7fb67544ac60, buf=0x1ab9660, frames=256)
    at /home/zonkmachine/builds/lmms/lmms/plugins/Delay/DelayEffect.cpp:123
#2  0x000000000050d2c5 in EffectChain::processAudioBuffer (this=0x1ab8d80, _buf=0x1ab9660, _frames=256, hasInputNoise=false)
    at /home/zonkmachine/builds/lmms/lmms/src/core/EffectChain.cpp:216
```

**Comment by zonkmachine** [comment]
I've got a fix for this and it needs testing. #3680
