### ISSUE TITLE
ubuntu studio + kxstudio repos: LMMS crash on start, repo version 1.1.3 and Appimage 1.2.0-rc7

### ISSUE THREAD

**Issue by antismap** [LMMS/lmms#4647]
Hi, 
I'm running ubuntu studio 18.04 64 bit with the kxstudio repositories. 
When starting lmms (Appimage version 1.2.0-rc7 or repo version 1.1.3), I'm getting: 

```
$ ./lmms-1.2.0-rc7-linux-x86_64.AppImage 
Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
Jack appears to be installed on this system, so we'll use it.
/tmp/.mount_lmms-1cwWDYt/usr/bin/lmms.real: /tmp/.mount_lmms-1cwWDYt/usr/lib/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)
QApplication: invalid style override passed, ignoring it.
VST sync support disabled in your configuration
free(): invalid pointer
/tmp/.mount_lmms-1cwWDYt/AppRun: line 23:  6958 Aborted                 (core dumped) QT_X11_NO_NATIVE_MENUBAR=1 $DIR/usr/bin/lmms.real "$@"
```

When running the system repo version through gdb, I'm getting:
```
[New Thread 0x7fffd7fff700 (LWP 6983)]
VST sync support disabled in your configuration
free(): invalid pointer

Thread 1 "lmms" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff528e801 in __GI_abort () at abort.c:79
#2  0x00007ffff52d7897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5404b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff52de90a in malloc_printerr (str=str@entry=0x7ffff5402d88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007ffff52e5e1c in _int_free (have_lock=0, p=0x7fffffffeb93, av=0x7ffff5639c40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x7fffffffeba3) at malloc.c:3124
#6  0x00007fffce8b2320 in ?? () from /usr/lib/ladspa/csladspa.so
#7  0x00007fffce8b2542 in ladspa_descriptor () from /usr/lib/ladspa/csladspa.so
#8  0x00000000004cffa4 in ladspaManager::addPlugins(_LADSPA_Descriptor const* (*)(unsigned long), QString const&) ()
#9  0x00000000004da95b in ladspaManager::ladspaManager() ()
#10 0x00000000004e9059 in ladspa2LMMS::ladspa2LMMS() ()
#11 0x00000000004b4c24 in engine::init(bool) ()
#12 0x0000000000481b9c in main ()
```

Thanks & Regards,

**Comment by PhysSong** [comment]
It seems like the csound LADSPA plugin is faulty. Can you remove that and test it again?

**Comment by antismap** [comment]
Where does this plugin come from? How to remove it ?
