### ISSUE TITLE
Ctrl-Drag to copy crashes LMMS with SIGSEGV

### ISSUE THREAD

**Issue by noahb01** [LMMS/lmms#4739]
This issue occurs regardless if it is an instrument-track, sample-track, etc.

When the crash occurs under `gdb` all mouse input across the entire desktop is frozen. The mouse can move, but cannot click/interact with anything, not even the KDE menu bar or other applications. Using `alt-tab` to switch to the terminal with `gdb` and typing `(gdb) continue` to let the LMMS process die restores normal operation of the mouse.

**LMMS Version**
```
~/Exec/lmms/build(master) » ./lmms --version
LMMS 1.2.0-rc7.391
(Linux x86_64, Qt 5.12.0, GCC 8.2.1 20181127)
```
**System Version**
```
Linux nbrecht-desktop 4.19.10-arch1-1-ARCH #1 SMP PREEMPT Tue Dec 18 00:04:08 UTC 2018 x86_64 GNU/Linux`
```
**Backtrace**
```
Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
0x00007ffff6076e26 in QCursor::shape() const () from /usr/lib/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff6076e26 in QCursor::shape() const () at /usr/lib/libQt5Gui.so.5
#1  0x00007ffff60a3a29 in QBasicDrag::updateCursor(Qt::DropAction) () at /usr/lib/libQt5Gui.so.5
#2  0x00007ffff148691c in  () at /usr/lib/libQt5XcbQpa.so.5
#3  0x00007ffff1487100 in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff1489c32 in  () at /usr/lib/libQt5XcbQpa.so.5
#5  0x00007ffff60a2766 in QBasicDrag::eventFilter(QObject*, QEvent*) () at /usr/lib/libQt5Gui.so.5
#6  0x00007ffff5c944db in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#7  0x00007ffff7a25e72 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff7a2d671 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff5c948f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff60689be in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#11 0x00007ffff6069e26 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#12 0x00007ffff604375c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#13 0x00007ffff148099c in  () at /usr/lib/libQt5XcbQpa.so.5
#14 0x00007ffff48b5a2f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff48b75e9 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff48b762e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff5cea5a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#18 0x00007ffff5c9358c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#19 0x00007ffff60a22a6 in QBasicDrag::drag(QDrag*) () at /usr/lib/libQt5Gui.so.5
#20 0x00007ffff609f9c6 in QDragManager::drag(QDrag*) () at /usr/lib/libQt5Gui.so.5
#21 0x00007ffff609fc8d in QDrag::exec(QFlags<Qt::DropAction>, Qt::DropAction) () at /usr/lib/libQt5Gui.so.5
#22 0x000055555577e757 in StringPairDrag::StringPairDrag(QString const&, QString const&, QPixmap const&, QWidget*) ()
#23 0x000055555571178a in TrackContentObjectView::mouseMoveEvent(QMouseEvent*) ()
#24 0x00007ffff7a669d8 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff7a25e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff7a2d8b9 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff5c948f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#28 0x00007ffff7a2cb98 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff7a81d2d in  () at /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff7a84c67 in  () at /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff7a25e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff7a2d671 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff5c948f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#34 0x00007ffff60689be in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#35 0x00007ffff6069e26 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#36 0x00007ffff604375c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#37 0x00007ffff148099c in  () at /usr/lib/libQt5XcbQpa.so.5
#38 0x00007ffff48b5a2f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#39 0x00007ffff48b75e9 in  () at /usr/lib/libglib-2.0.so.0
#40 0x00007ffff48b762e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#41 0x00007ffff5cea5a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#42 0x00007ffff5c9358c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#43 0x00007ffff5c9b896 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#44 0x0000555555652bb3 in main ()
```

**Comment by CYBERDEViLNL** [comment]
See https://github.com/LMMS/lmms/issues/4738

**Comment by noahb01** [comment]
Just confirmed that I am also unable to drag-and-drop instruments, so this is the same bug as #4738.

Closing as duplicate.
