### ISSUE TITLE
Drag+Drop is broken

### ISSUE THREAD

**Issue by RiedleroD** [LMMS/lmms#6291]
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

### Bug Summary

I can't drop anything anymore - dragging technically works, but when I try to drop whatever is being dragged, nothing happens.

#### Steps to reproduce

presumable only reproducable on newest arch linux with wayland and master

drag an instrument into the instrument panel

#### Expected behavior

instrument gets dropped in the instrument panel

#### Actual behavior

after dropping, no instrument is added and the cursor starts behaving oddly (switches from dragging icon to pointer icon randomly)

#### Affected LMMS versions

Every master I tried to compile - not 1.2.2 stable though, even if compiled manually.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
Notice: could not set realtime priority.
Lv2 plugin SUMMARY: 5 of 29  loaded in 7 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QDragManager::drag in possibly invalid state
</pre>
</details>

**Comment by cyber-bridge** [comment]
Can you try starting LMMS with `QT_QPA_PLATFORM=xcb lmms`?

**Comment by RiedleroD** [comment]
> Can you try starting LMMS with QT_QPA_PLATFORM=xcb lmms?

That's how I tested XWayland compatibility.

> possible related (#3466)

idk, possibly similar in origin, but that one seems to have been resolved upstream. Doesn't really sound like something that could've been fixed in LMMS, too.

**Comment by djnotes** [comment]
@cyber-bridge it's weird. When I start it with the QT_QPA_PLATFORM=xcb, the drag and drop works on Fedora.

**Comment by Grissess** [comment]
Friends! I think I've been bitten with this on 5904b24 (the current `master` as of this writing). This is a source-based Linux with Sway, so things tend to be painfully new. `QT_QPA_PLATFORM=xcb` works, but is just one more thing to remember :)

Mouse input works for the most part, _except_ for click and drag, which utterly fails. When trying to start another drag (or, I swear, on occasion on exit), I get this line in the tty:

```
QDragManager::drag in possibly invalid state
```

... after each subsequent attempt to start a drag. (I'm pulling instrument plugins into the song editor as my test case.)

On some occasions, even with the main UI closed, in the state after a drag has failed (hung?), the app doesn't shut down properly, and has to be `^C`'d in the terminal (lacking any other interface to do so).

I'm open to testing hypotheses as you have them :)

**Comment by Rossmaxx** [comment]
I remember someone talking about this issue before on discord and also about some sort of a workaround. Maybe @zonkmachine might know.

**Comment by zonkmachine** [comment]
> I remember someone talking about this issue before on discord and also about some sort of a workaround. Maybe @zonkmachine might know.

I know of no workaround. I do remember several previous issues with drag/drop, possibly unrelated, but I believe they were all
A. Qt issues (upstream)
B. All supposedly fixed

I personally only see issues with drag/drop when compiling with the fpe debug flags.

```cpp
Thread 1 "lmms" received signal SIGFPE, Arithmetic exception.
0x00007ffff6a55215 in QBasicDrag::startDrag() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt full
#0  0x00007ffff6a55215 in QBasicDrag::startDrag() () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007ffff1e59eca in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#2  0x00007ffff6a53f92 in QBasicDrag::drag(QDrag*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff6a513e9 in QDragManager::drag(QDrag*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
```

**Comment by zonkmachine** [comment]
For the record. This is only affecting some builds and I would guess this isn't a problem on our side.

**Comment by tresf** [comment]
This may be a duplicate of #2890, near identical symptom.

Specifically, in #2890 we noticed that QDrag is very picky about which shortcut key it uses.   We're working to patch this in #7325.  In the case of macOS, certain versions of Qt would not permit a drag shortcut to different from QDrag's built-in modifiers.  Here's the commit: https://github.com/LMMS/lmms/pull/7325/commits/304bce36349ff8199ac99cba3387df4ea3b673f2.

Note, this commit doesn't fix Linux specifically, but may offer some insight as to the problem.
