### ISSUE TITLE
"show GUI" button doesn't work for Carla on Linux

### ISSUE THREAD

**Issue by Duskhorn** [LMMS/lmms#6315]
### Bug Summary
Carla (both rack and patchbay) doesn't load when clicking on the "show GUI" 

#### Steps to reproduce
Clicking the "Show GUI" button in the synth menu

#### Expected behavior
Carla opens and loads correctly

#### Actual behavior
Carla doesn't open. Debug console displays 
```
Trying to start carla-plugin using "//share/carla/resources/carla-plugin"
exec failed: No such file or directory
waitForClientFirstMessage() - read returned 0
```

#### Affected LMMS versions
1.2.2 64bit Linux AppImage downloaded from the official website

**Comment by mikobuntu** [comment]
@Duskhorn Works ok for me , are you sure that you have carla installed on your system ? I believe that the carla plugins in LMMS are just a frontend for the system version of carla.

**Comment by PhysSong** [comment]
Further inspection on Discord(with `LD_DEBUG=files`):
```
      1553:    file=libcarla_native-plugin.so [0];  needed by /tmp/.mount_lmms.A2S5rLy/usr/lib/lmms/libcarlabase.so [0]
      1553:    file=libcarla_native-plugin.so [0];  generating link map
      1553:    file=libfluidsynth.so.3 [0];  needed by /lib/carla/libcarla_native-plugin.so [0]
      1553:    file=liblo.so.7 [0];  needed by /lib/carla/libcarla_native-plugin.so [0]
      1553:    file=libmagic.so.1 [0];  needed by /lib/carla/libcarla_native-plugin.so [0]
      1553:    calling init: /lib/carla/libcarla_native-plugin.so
```
For some reason, Carla is loaded from `/lib`(not from `/usr/lib` as in usual cases) and causing issues because `/lib/../share` is `/share`.

**Comment by Nefor111** [comment]
Arch Linux
Lmms 1.2.2
carla-git from AUR repository

Well the problem is - then "show GUI" key is pressed 

carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 848, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
[carla] waitForClientFirstMessage() - read returned 0


Then installed module utils via pip3 install utils following errors appear

[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 848, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ImportError: cannot import name 'QSafeSettings' from 'utils' (/home/neff/.local/lib/python3.10/site-packages/utils/__init__.py)
[carla] waitForClientFirstMessage() - read returned 0

Stand alone version is working without any issue.

**Comment by Arnesfield** [comment]
Also experienced the same issue by @Nefor111. I don't have experience with Python, but I was able to resolve the issue by creating symlinks pointing to `utils` and `pluginlist` in the `resources` directory.

Go to resources:

```sh
cd /usr/share/carla/resources
```

Create symlink to `utils`:

```sh
sudo ln -s ../utils utils
```

Doing this fixes the `from utils import QSafeSettings` error, but it shows a new error with `pluginlist`:

```
[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin-patchbay"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin-patchbay", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 64, in <module>
    from pluginlist import PluginDatabaseW
ModuleNotFoundError: No module named 'pluginlist'
[carla] waitForClientFirstMessage() - read returned 0
```

Fixed by also creating a symlink pointing to `pluginlist` within `resources`:

```sh
sudo ln -s ../pluginlist pluginlist
```

"Show GUI" works now after creating these symlinks.

I assume this is a workaround rather than an actual fix. I'd be happy if there's a better solution, but until the issue is resolved, hope this workaround helps.

**Comment by ctxmc** [comment]
Hello. I had this same issue, but I tried to build Carla from source.
In this case, what was missing is that we need and want the carla frontend, as described in the [INSTALL.md](https://github.com/falkTX/Carla/blob/main/INSTALL.md):

we can use:
`make features`

to see if the frontend dependencies are there and if not you need to install it. 

In case of debian: 
```
sudo apt install python3-pyqt5.qtsvg python3-rdflib pyqt5-dev-tools \
  libmagic-dev liblo-dev libasound2-dev libpulse-dev libx11-dev libxcursor-dev libxext-dev \
  qtbase5-dev libfluidsynth-dev
```

and an sudo make install will just do the trick and the gui will open ;)
