### ISSUE TITLE
mod-pitchshifter, Capo - Crash

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#6494]
Crash with Capo from the mod-pitchshifter plugins. https://github.com/moddevices/mod-pitchshifter

#### Steps to reproduce
Insert a Capo pitch shifter into a track and change fidelity/steps while playing.

#### Affected LMMS versions
On master (4821606465a5c46109f048466f84e55aeeb31d6e) with LV2_BUF_SIZE__powerOf2BlockLength supported as described in https://github.com/LMMS/lmms/issues/6492
The crashes don't seem to occur on buffer sizes 64 and 128

There is a `free(): invalid pointer` in the log ahead of the crash on the first backtrace and `malloc_consolidate(): invalid chunk size` in the second one so I think this could be the plugin doing something it shouldn't.

#### bt full
<details>
  <summary>Click to expand</summary>
<pre>
$ gdb ./lmms 
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
...
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./lmms...
(gdb) r
Starting program: /home/zonkmachine/builds/lmms/build/lmms 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
*** WEAK-JACK: initializing
*** WEAK-JACK: OK. (0)
...
[New Thread 0x7fffaeffd640 (LWP 6622)]
[New Thread 0x7fffae7fc640 (LWP 6623)]
Lv2 plugin SUMMARY: 453 of 664  loaded in 1282 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
Lv2 Plugins blacklisted: 67 of 664 
  If you want to ignore the blacklist (dangerous!), please set
  environment variable "LMMS_IGNORE_BLACKLIST" to nonempty.
[New Thread 0x7fffad3e3640 (LWP 6624)]
[New Thread 0x7fff4bfff640 (LWP 6625)]
...
PSSinthesis: using plugin-provided wisdom file
PSAnalysis: using plugin-provided wisdom file
PSSinthesis: using plugin-provided wisdom file
free(): invalid pointer

Thread 37 "AudioEngine::fi" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff4a7fc640 (LWP 6628)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140734443275840) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt full
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140734443275840) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7fff4a7fc640

                    old_mask = {__val = {13868027264701280454, 13881373980794468736, 4689042460723314558, 4696504442404442772, 4687337332942627818, 4671254037622849825, 13898197651175640346, 13903713926783446194, 13896656505244863382, 13895600226758994591, 13858985664912450970, 13876905479650613322, 13874934609359434761, 13846077140705479435, 4670642992624877314, 4653135666552268771}}
        ret = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140734443275840) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140734443275840, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff5e5a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007ffff5e407f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1

                  act = {__sigaction_handler = {sa_handler = 0x3ec91ed840360a88, sa_sigaction = 0x3ec91ed840360a88}, sa_mask = {__val = {13872782781353883864, 13820610997546793218, 4544451287203375540, 4655123972268337148, 4553725420803670418, 4597662253350026347, 4548312411250504440, 13705419212313940393, 4619114807532597416, 4632578243637880612, 4638502637791367339, 4652546326167234582, 65535, 140734443272096, 93824994479830, 140734443272112}}, sa_flags = -160335208, sa_restorer = 0x0}

                    sigs = {__val = {32, 4675140141224373941, 4677718448747764169, 4680354532170865989, 13904041392275949590, 13908495814528788271, 13909287875218221746, 13910387915127020646, 13890723954965191768, 13881034384188588280, 13861448027642039878, 13824286896839888175, 13850167966052229945, 13818963083016108740, 13728551803069777248, 4550859840096576881}}
#5  0x00007ffff5ea16f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5ff3b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
        ap = {{gp_offset = 24, fp_offset = 0, overflow_arg_area = 0x7fff4a7fb8d0, reg_save_area = 0x7fff4a7fb860}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#6  0x00007ffff5eb8d7c in malloc_printerr (str=str@entry=0x7ffff5ff1764 "free(): invalid pointer") at ./malloc/malloc.c:5664
#7  0x00007ffff5ebaac4 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4439
        size = 0
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        __PRETTY_FUNCTION__ = "_int_free"
--Type <RET> for more, q to quit, c to continue without paging--
#8  0x00007ffff5ebd4d3 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
        ar_ptr = <optimized out>
        p = <optimized out>
        err = 2
#9  0x00005555557bef31 in QTypedArrayData<lmms::Track*>::deallocate(QArrayData*) (data=0x7fff24008f70) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:239
#10 0x00005555557bd3ce in QVector<lmms::Track*>::realloc(int, QFlags<QArrayData::AllocationOption>) (this=0x7fff4a7fba98, aalloc=5, options=...)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:745
        x = 0x7fffa4020740
        isShared = false
#11 0x00005555557bb57c in QVector<lmms::Track*>::operator+=(QVector<lmms::Track*> const&) (this=0x7fff4a7fba98, l=...)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:978
        opt = {i = 8}
        newSize = 5
        isTooSmall = true
#12 0x00005555558645ff in QVector<lmms::Track*>::operator<<(QVector<lmms::Track*> const&) (this=0x7fff4a7fba98, l=...)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:295
#13 0x000055555585f136 in lmms::Song::automatedValuesAt(lmms::TimePos, int) const (this=0x5555568332b0, time=..., clipNum=-1)
    at /home/zonkmachine/builds/lmms/src/core/Song.cpp:851
#14 0x000055555585d72f in lmms::Song::processAutomations(QVector<lmms::Track*> const&, lmms::TimePos, short) (this=0x5555568332b0, tracklist=..., timeStart=...)
    at /home/zonkmachine/builds/lmms/src/core/Song.cpp:386
        values = {d = 0x7ffff6718620 <QMapDataBase::shared_null>}
        recordedModels = {q_hash = {{d = 0x7ffff6718560 <QHashData::shared_null>, e = 0x7ffff6718560 <QHashData::shared_null>}}}
        container = 0x5555568332b0
        clipNum = -1
        tracks = {d = 0x5555568334a0}
        clips = {d = 0x7fff4a7fbb30}
#15 0x000055555585d370 in lmms::Song::processNextBuffer() (this=0x5555568332b0) at /home/zonkmachine/builds/lmms/src/core/Song.cpp:342
        frameOffsetInTick = 0.75
        framesUntilNextPeriod = 189
        framesUntilNextTick = 393
        framesToPlay = 189
        trackList = {d = 0x55555c8e39f0}
        clipNum = -1
        enforceLoop = {__this = 0x5555568332b0}
        timeline = 0x55555c44e430
        loopEnabled = true
        framesPerTick = 393.75
        framesPerPeriod = 256
        frameOffsetInPeriod = 67
#16 0x00005555557a4882 in lmms::AudioEngine::renderNextBuffer() (this=0x5555566ceb60) at /home/zonkmachine/builds/lmms/src/core/AudioEngine.cpp:380
--Type <RET> for more, q to quit, c to continue without paging--
        it_rem = {i = 0x7fff240025f0}
        mixer = 0x555556809fb0
#17 0x00005555557a751b in lmms::AudioEngine::fifoWriter::run() (this=0x7fffec005e20) at /home/zonkmachine/builds/lmms/src/core/AudioEngine.cpp:1265
        buffer = 0x7fff24007b00
        b = 0x555556830b50
        frames = 256
#18 0x00007ffff643fca1 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff5eacb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>

                      unwind_buf = {cancel_jmp_buf = {{jmp_buf = {4294967295, 5935667620769944738, 140734443275840, 11, 140737319192656, 140737488345184, 5935667619191837858, 5935398420712117410}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#20 0x00007ffff5f3ea00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 

</pre>
</details>

#### bt full
<details>
  <summary>Click to expand</summary>
<pre>
PSAnalysis: using plugin-provided wisdom file
PSSinthesis: using plugin-provided wisdom file
malloc_consolidate(): invalid chunk size

Thread 30 "lmms::AudioEngi" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffaf7fe640 (LWP 7968)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140736137782848) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt full
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736137782848) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7fffaf7fe640

                    old_mask = {__val = {13483024875809953566, 13545356318840025286, 13578244721665563699, 13566951843881746214, 4220835407719236179, 13487615459252654027, 4246687492307906326, 4335562159660654778, 13421696384962596848, 4284969369068773168, 4344439492000768449, 4364971767842364374, 13553673641112806885, 13562453241461464637, 32, 1024}}
        ret = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140736137782848) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736137782848, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff5e5a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007ffff5e407f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1

                  act = {__sigaction_handler = {sa_handler = 0xbf5307103e158cae, sa_sigaction = 0xbf5307103e158cae}, sa_mask = {__val = {13765424801656685679, 13684812489623344646, 4434739826513928633, 4508661260268082415, 4513837889861101426, 4488374312928176171, 4494650471318488128, 4501399774087927479, 4536404715333764628, 4492156106825116008, 4493206720236444715, 4444340027604366542, 13716465118710935846, 13692643937293160104, 4445822405513167315, 4489255331015977370}}, sa_flags = 1062997599, sa_restorer = 0x3e3825023e08c1f4}

                    sigs = {__val = {32, 13728648076917467936, 4535446198877753044, 4478860520128988450, 13689495292457165232, 13730695135630781208, 13735948185578313952, 13774521252489505478, 13788819866493637902, 13786215866483398886, 4587109596001800152, 4581060886183490034, 4570736665267836522, 4528084431669643971, 13783395054374394403, 13790630760005002156}}
#5  0x00007ffff5ea16f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5ff3b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
        ap = {{gp_offset = 24, fp_offset = 7, overflow_arg_area = 0x7fffaf7fd820, reg_save_area = 0x7fffaf7fd7b0}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#6  0x00007ffff5eb8d7c in malloc_printerr (str=str@entry=0x7ffff5ff6610 "malloc_consolidate(): invalid chunk size") at ./malloc/malloc.c:5664
#7  0x00007ffff5eb9a28 in malloc_consolidate (av=av@entry=0x7fff98000030) at ./malloc/malloc.c:4755
        idx = <optimized out>
        fb = 0x7fff98000048
        maxfb = 0x7fff98000088
        p = 0x7fff9800e800
        nextp = <optimized out>
        unsorted_bin = 0x7fff98000090
        first_unsorted = <optimized out>
        nextchunk = <optimized out>
        size = <optimized out>
        nextsize = <optimized out>
        prevsize = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        nextinuse = <optimized out>
#8  0x00007ffff5ebbc5b in _int_malloc (av=av@entry=0x7fff98000030, bytes=bytes@entry=2624) at ./malloc/malloc.c:3965
        nb = 2640
        idx = 89
        bin = <optimized out>
        victim = <optimized out>
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        tcache_unsorted_count = <optimized out>
        tcache_nb = <optimized out>
        tc_idx = <optimized out>
        return_cached = <optimized out>
        __PRETTY_FUNCTION__ = "_int_malloc"
#9  0x00007ffff5ebd1b9 in __GI___libc_malloc (bytes=2624) at ./malloc/malloc.c:3329
        ar_ptr = 0x7fff98000030
        victim = <optimized out>
        tbytes = <optimized out>
        __PRETTY_FUNCTION__ = "__libc_malloc"
#10 0x00007ffff61f5a0c in operator new(unsigned long) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007fffe81e140b in Capo::run(void*, unsigned int) () at /usr/local/lib/lv2/mod-capo.lv2/mod-capo.so
#12 0x0000555555890729 in lilv_instance_run(LilvInstance*, uint32_t) (instance=0x55555d1ab960, sample_count=256) at /usr/include/lilv-0/lilv/lilv.h:1948
#13 0x0000555555891ae2 in lmms::Lv2Proc::run(short) (this=0x55555d1b2da0, frames=256) at /home/zonkmachine/builds/lmms/src/core/lv2/Lv2Proc.cpp:334
#14 0x00005555558888e8 in lmms::Lv2ControlBase::run(short) (this=0x7ffff2793e50, frames=256) at /home/zonkmachine/builds/lmms/src/core/lv2/Lv2ControlBase.cpp:151
        c = std::unique_ptr<lmms::Lv2Proc> = {get() = 0x55555d1b2da0}

                    __for_range = std::vector of length 2, capacity 2 = {std::unique_ptr<lmms::Lv2Proc> = {get() = 0x55555d2f4620}, std::unique_ptr<lmms::Lv2Proc> = {get() = 0x55555d1b2da0}}
        __for_begin = std::unique_ptr<lmms::Lv2Proc> = {get() = 0x55555d1b2da0}
        __for_end = std::unique_ptr<lmms::Lv2Proc> = {get() = 0x180}
#15 0x00007fffac688e9c in lmms::Lv2Effect::processAudioBuffer(std::array<float, 2ul>*, short) (this=0x7ffff2793880, buf=0x7ffff2793080, frames=256)
    at /home/zonkmachine/builds/lmms/plugins/Lv2Effect/Lv2Effect.cpp:79
        outSum = 4.6355770498214659e-310
        corrupt = 85
        d = 0
        w = 0
#16 0x00005555557f6c7c in lmms::EffectChain::processAudioBuffer(std::array<float, 2ul>*, short, bool)
    (this=0x55555c9bfcd0, _buf=0x7ffff2793080, _frames=256, hasInputNoise=true) at /home/zonkmachine/builds/lmms/src/core/EffectChain.cpp:201
        it = 0x55555d304808
        moreEffects = false

</pre>
</details>

**Comment by zonkmachine** [comment]
Possibly https://github.com/moddevices/mod-pitchshifter/issues/12

**Comment by zonkmachine** [comment]
```gdb
#15 0x00007fffac688e9c in lmms::Lv2Effect::processAudioBuffer(std::array<float, 2ul>, short) (this=0x7ffff2793880, buf=0x7ffff2793080, frames=256)

at /home/zonkmachine/builds/lmms/plugins/Lv2Effect/Lv2Effect.cpp:79
outSum = 4.6355770498214659e-310
corrupt = 85
d = 0
w = 0
```
From backtrace 2 above. Why does the bool corrupt come up with a value of 85?

**Comment by zonkmachine** [comment]
#### Valgrind
`This is probably caused by your program erroneously writing past the end of a heap block and corrupting heap metadata.`

Looks like it's in Capo and not lmms, though I'm not experienced with Valgrind. I don't know how to turn on a debug build in mod-pitchshifter.

```gdb
$~/builds/lmms/build$ valgrind --smc-check=all --error-limit=no --leak-check=no ./lmms render ~/Documents/lmms/projects/capobitinvader.mmp -o test
==33755== Memcheck, a memory error detector
==33755== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==33755== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==33755== Command: ./lmms render /home/zonkmachine/Documents/lmms/projects/capobitinvader.mmp -o test
==33755== 
*** WEAK-JACK: initializing
*** WEAK-JACK: OK. (0)

...

|------------                                      |     23%   /  PSAnalysis: using plugin-provided wisdom file
PSSinthesis: using plugin-provided wisdom file
PSAnalysis: using plugin-provided wisdom file
PSSinthesis: using plugin-provided wisdom file
|-----------------                                 |     32%   |  PSAnalysis: using plugin-provided wisdom file
|------------------                                |     34%   /  PSSinthesis: using plugin-provided wisdom file
==33755== Thread 10 lmms::ProjectRen:
==33755== Invalid write of size 8
==33755==    at 0x48527ED: memset (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==33755==    by 0x1CF00139: PSSinthesis::Sinthesis(double) (in /usr/local/lib/lv2/mod-capo.lv2/mod-capo.so)
==33755==    by 0x1CEF331B: Capo::run(void*, unsigned int) (in /usr/local/lib/lv2/mod-capo.lv2/mod-capo.so)
==33755==    by 0x444728: lilv_instance_run (lilv.h:1948)
==33755==    by 0x445AE1: lmms::Lv2Proc::run(short) (Lv2Proc.cpp:334)
==33755==    by 0x43C8E7: lmms::Lv2ControlBase::run(short) (Lv2ControlBase.cpp:151)
==33755==    by 0x1BFE9E9B: lmms::Lv2Effect::processAudioBuffer(std::array<float, 2ul>*, short) (Lv2Effect.cpp:79)
==33755==    by 0x3AAC7B: lmms::EffectChain::processAudioBuffer(std::array<float, 2ul>*, short, bool) (EffectChain.cpp:201)
==33755==    by 0x3B367B: lmms::MixerChannel::doProcessing() (Mixer.cpp:173)
==33755==    by 0x36113E: lmms::ThreadableJob::process() (ThreadableJob.h:77)
==33755==    by 0x3609EB: lmms::AudioEngineWorkerThread::JobQueue::run() (AudioEngineWorkerThread.cpp:88)
==33755==    by 0x360CEC: lmms::AudioEngineWorkerThread::startAndWaitForJobs() (AudioEngineWorkerThread.cpp:161)
==33755==  Address 0x17a3ad50 is 16 bytes after a block of size 32 alloc'd
==33755==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==33755==    by 0x6DA3EE5: sord_add (in /usr/lib/x86_64-linux-gnu/libsord-0.so.0.16.8)
==33755==    by 0x6DA49B9: sord_inserter_write_statement (in /usr/lib/x86_64-linux-gnu/libsord-0.so.0.16.8)
==33755==    by 0x6D91699: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D887EC: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D89EE5: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D8A520: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D887AE: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D89EE5: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D8A520: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D887AE: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755==    by 0x6D8A35B: ??? (in /usr/lib/x86_64-linux-gnu/libserd-0.so.0.30.10)
==33755== 
==33755== Invalid write of size 8
==33755==    at 0x48527F7: memset (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==33755==    by 0x1CF00139: PSSinthesis::Sinthesis(double) (in /usr/local/lib/lv2/mod-capo.lv2/mod-capo.so)
==33755==    by 0x1CEF331B: Capo::run(void*, unsigned int) (in /usr/local/lib/lv2/mod-capo.lv2/mod-capo.so)
==33755==    by 0x444728: lilv_instance_run (lilv.h:1948)
==33755==    by 0x445AE1: lmms::Lv2Proc::run(short) (Lv2Proc.cpp:334)
==33755==    by 0x43C8E7: lmms::Lv2ControlBase::run(short) (Lv2ControlBase.cpp:151)
==33755==    by 0x1BFE9E9B: lmms::Lv2Effect::processAudioBuffer(std::array<float, 2ul>*, short) (Lv2Effect.cpp:79)
==33755==    by 0x3AAC7B: lmms::EffectChain::processAudioBuffer(std::array<float, 2ul>*, short, bool) (EffectChain.cpp:201)
==33755==    by 0x3B367B: lmms::MixerChannel::doProcessing() (Mixer.cpp:173)
==33755==    by 0x36113E: lmms::ThreadableJob::process() (ThreadableJob.h:77)
==33755==    by 0x3609EB: lmms::AudioEngineWorkerThread::JobQueue::run() (AudioEngineWorkerThread.cpp:88)
==33755==    by 0x360CEC: lmms::AudioEngineWorkerThread::startAndWaitForJobs() (AudioEngineWorkerThread.cpp:161)
==33755==  Address 0x17a3ad58 is 24 bytes after a block of size 32 in arena "client"
==33755== 

valgrind: m_mallocfree.c:303 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 96, hi = 0.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.


host stacktrace:
==33755==    at 0x5804284A: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x58042977: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x58042B1B: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x5804C8CF: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x5803AE9A: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x580395B7: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x5803DF3D: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x58038868: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x100428E518: ???
==33755==    by 0x1012E38F1F: ???
==33755==    by 0x581FCD83: ??? (in /usr/libexec/valgrind/memcheck-amd64-linux)
==33755==    by 0x1012E38F07: ???
==33755==    by 0x1012E38F1F: ???
==33755==    by 0x9: ???
==33755==    by 0x2DA6: ???

...

Thread 10: status = VgTs_Runnable (lwpid 33775)
==33755==    at 0x48527FB: memset (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==33755==    by 0x1CF00139: PSSinthesis::Sinthesis(double) (in /usr/local/lib/lv2/mod-capo.lv2/mod-capo.so)
==33755==    by 0x1CEF331B: Capo::run(void*, unsigned int) (in /usr/local/lib/lv2/mod-capo.lv2/mod-capo.so)
==33755==    by 0x444728: lilv_instance_run (lilv.h:1948)
==33755==    by 0x445AE1: lmms::Lv2Proc::run(short) (Lv2Proc.cpp:334)
==33755==    by 0x43C8E7: lmms::Lv2ControlBase::run(short) (Lv2ControlBase.cpp:151)
==33755==    by 0x1BFE9E9B: lmms::Lv2Effect::processAudioBuffer(std::array<float, 2ul>*, short) (Lv2Effect.cpp:79)
==33755==    by 0x3AAC7B: lmms::EffectChain::processAudioBuffer(std::array<float, 2ul>*, short, bool) (EffectChain.cpp:201)
==33755==    by 0x3B367B: lmms::MixerChannel::doProcessing() (Mixer.cpp:173)
==33755==    by 0x36113E: lmms::ThreadableJob::process() (ThreadableJob.h:77)
==33755==    by 0x3609EB: lmms::AudioEngineWorkerThread::JobQueue::run() (AudioEngineWorkerThread.cpp:88)
==33755==    by 0x360CEC: lmms::AudioEngineWorkerThread::startAndWaitForJobs() (AudioEngineWorkerThread.cpp:161)
==33755==    by 0x3B5178: lmms::Mixer::masterMix(std::array<float, 2ul>*) (Mixer.cpp:647)
==33755==    by 0x358AE6: lmms::AudioEngine::renderNextBuffer() (AudioEngine.cpp:427)
==33755==    by 0x34A124: lmms::AudioEngine::nextBuffer() (AudioEngine.h:345)
==33755==    by 0x42ADC0: lmms::AudioDevice::getNextBuffer(std::array<float, 2ul>*) (AudioDevice.cpp:85)
==33755==    by 0x42AD23: lmms::AudioDevice::processNextBuffer() (AudioDevice.cpp:68)
==33755==    by 0x3FC17B: lmms::ProjectRenderer::run() (ProjectRenderer.cpp:188)
==33755==    by 0x6010CA0: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.3)
==33755==    by 0x686AB42: start_thread (pthread_create.c:442)
==33755==    by 0x68FBBB3: clone (clone.S:100)
client stack range: [0x39205000 0x39A03FFF] client SP: 0x39A03758
valgrind stack range: [0x1012D39000 0x1012E38FFF] top usage: 6920 of 1048576


Note: see also the FAQ in the source distribution.
It contains workarounds to several common problems.
In particular, if Valgrind aborted or crashed after
identifying problems in your program, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing, especially if it happened in m_mallocfree.c.

If that doesn't help, please report this bug to: www.valgrind.org

In the bug report, send all the above text, the valgrind
version, and what OS and version you are using.  Thanks.
```

**Comment by zonkmachine** [comment]
Closed upstream in https://github.com/moddevices/mod-pitchshifter/commit/efd26e6b02ddf9683ffae00a59ad72b5ab59d585
