### ISSUE TITLE
For an unknown reason Carla loads into LMMS without crashing, but can't access the GUI.

### ISSUE THREAD

**Issue by cheez26** [LMMS/lmms#6546]
Long story short, I compiled LMMS on my Raspberry Pi 400 and made sure to install Carla before compiling it.
Some people have noted on Discord that the GUI is slow to show on x86_64 devices despite having six-core CPU and 12 GB of RAM. As for me, the GUI won't show up at all on my ARM64 device.

Is this a common bug or am I doing something wrong?

**Comment by cheez26** [comment]
Here's what I got in the terminal output.

```
[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 58, in <module>
    from carla_frontend import CarlaFrontendLib
ModuleNotFoundError: No module named 'carla_frontend'
[carla] waitForClientFirstMessage() - read returned 0
[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 58, in <module>
    from carla_frontend import CarlaFrontendLib
ModuleNotFoundError: No module named 'carla_frontend'
[carla] waitForClientFirstMessage() - read returned 0



```

**Comment by kamkamkamkamkamkamkamkam** [comment]
I'm having the same problem on Debian amd64 on a master branch build of LMMS, thought with a different error.
```[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 847, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
[carla] waitForClientFirstMessage() - read returned 0
[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 847, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
[carla] waitForClientFirstMessage() - read returned 0


```

**Comment by cheez26** [comment]
I'm not gonna close the issue yet. I just installed a different version of Carla. I'm gonna test it out for a bit and see what happens.

**Comment by cheez26** [comment]
Well...it seems that I fixed my end, but I'm not so sure about kam tbh. :(

**Comment by cheez26** [comment]
I think this is less of a Carla issue rather than a LMMS issue. Henceforth...this is now closed. Sorry about the mess.

**Comment by djent** [comment]
Just had the same issue of the Carla gui not loading. 

Fixed by changing the symbolic links for `carla_frontend.py` and `carla_host.py` to absolute paths.

**In `/usr/share/carla/resources`, the following commands worked for me:**

```
sudo ln -s /usr/share/carla/carla_frontend.py carla_frontend.py
sudo ln -sf /usr/share/carla/carla_host.py carla_host.py

```
**This was the error, I received when trying to open carla gui:**

```
[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin-patchbay"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin-patchbay", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 58, in <module>
    from carla_frontend import CarlaFrontendLib
ModuleNotFoundError: No module named 'carla_frontend'
[carla] waitForClientFirstMessage() - read returned 0

```
