### ISSUE TITLE
Compressor - Arithmetic exception

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#6853]
### Bug Summary
The Native compressor has some default variable values that gives an arithmetic exception on debugging.

#### Steps to reproduce
On Linux
1 - Compile lmms with debug AND fpe flags set:
`cmake -DCMAKE_BUILD_TYPE=Debug -DWANT_DEBUG_FPE=ON`

2 - Download and rename this project to `Boss Fight Lead 2.xpf`
[Boss Fight Lead 2.txt](https://github.com/LMMS/lmms/files/12552100/Boss.Fight.Lead.2.txt)

3 - Start lmms in gdb
` gdb ./lmms`

4 - Preview Boss Fight Lead 2. Crash.

Debugging with the FPE extensions points to this line:
https://github.com/LMMS/lmms/blob/de062d6c54d48cc53d080fb25ed33a6c72d6e26f/plugins/Compressor/Compressor.cpp#L325

@LostRobotMusic 

#### Logs of crash with FPE activated
<details>
  <summary>Click to expand</summary>
<pre>
Thread 28 "lmms::AudioEngi" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffaffff640 (LWP 25046)]
0x00007fff7867f70b in lmms::CompressorEffect::processAudioBuffer (this=0x7ffff2860080, buf=0x7ffff27a1080, frames=256) at /home/zonkmachine/builds/lmms/plugins/Compressor/Compressor.cpp:325
325				m_crestFactorVal[i] = m_crestPeakVal[i] / m_crestRmsVal[i];
(gdb) bt full
#0  0x00007fff7867f70b in lmms::CompressorEffect::processAudioBuffer(std::array<float, 2ul>*, short) (this=0x7ffff2860080, buf=0x7ffff27a1080, frames=256)
    at /home/zonkmachine/builds/lmms/plugins/Compressor/Compressor.cpp:325
        inputValue = 0
        t = 4.59163468e-41
        currentPeakDbfs = 3.91734827e+17
        i = 0
        drySignal = {_M_elems = {0, 0}}
        s = {_M_elems = {0, 0}}
        temp1 = 1.40129846e-45
        delayedDrySignal = {_M_elems = {-4.65512517e-10, 4.59163468e-41}}
        temp2 = 0
        f = 0
        outSum = 0
        d = 0
        w = 1
        lOutPeak = 0
        rOutPeak = 0
        lInPeak = 0
        rInPeak = 0
        midside = false
        peakmode = false
        inBalance = 0
        outBalance = 0
        limiter = true
        blend = 1
        stereoBalance = 0
        autoMakeup = false
        stereoLink = 1
        audition = false
        feedback = false
        lookahead = false
#1  0x000055555582d5fa in lmms::EffectChain::processAudioBuffer(std::array<float, 2ul>*, short, bool) (this=0x55555cadf6e0, _buf=0x7ffff27a1080, _frames=256, hasInputNoise=true)
    at /home/zonkmachine/builds/lmms/src/core/EffectChain.cpp:201
        effect = @0x55555d16d8a0: 0x7ffff2860080
        __for_range = std::vector of length 2, capacity 2 = {0x7ffff2860080, 0x7ffff27a1880}
        __for_begin = 0x7ffff2860080
        __for_end = 0x2
        moreEffects = false
</pre>
</details>

**Comment by zonkmachine** [comment]
Sorry. The noise seem to be in the Calf Multiband Enhancer LADSPA. The Arithmetic exception is still there however.
