### ISSUE TITLE
Automating chord stacking leads to occasional segfaults

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#7010]
Hi,

Clearly not reproductible, it some times happens, and some times not, I rerun the program and it doesn’t happen again. Just playing the song it crashes with 

```
Thread 22 "lmms::AudioEngi" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa77fe6c0 (LWP 2245)]
0x000055555584a0e6 in lmms::InstrumentFunctionNoteStacking::Chord::size (this=0x55455c7f2000) at /usr/local/src/lmms/include/InstrumentFunctions.h:90
90				return m_size;
(gdb) bt full
#0  0x000055555584a0e6 in lmms::InstrumentFunctionNoteStacking::Chord::size() const (this=0x55455c7f2000) at /usr/local/src/lmms/include/InstrumentFunctions.h:90
#1  0x0000555555847ac0 in lmms::InstrumentFunctionNoteStacking::processNote(lmms::NotePlayHandle*) (this=0x7fff0c6465c0, _n=0x7ffff2a4f580)
    at /usr/local/src/lmms/src/core/InstrumentFunctions.cpp:249
        i = 0
        sub_note_key_base = 57
        octave_cnt = 0
        selected_chord = -2147483648
        base_note_key = 57
        chord_table = @0x555555c724d0: {static s_initTable = {_M_elems = {{m_name = 0x555555a6c0e0 "octave", m_semiTones = {_M_elems = "\000\377\000\000\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c0e7 "Major", m_semiTones = {_M_elems = "\000\004\a\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c0ed "Majb5", m_semiTones = {_M_elems = "\000\004\006\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c0f3 "minor", m_semiTones = {_M_elems = "\000\003\a\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c0f9 "minb5", m_semiTones = {_M_elems = "\000\003\006\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c0ff "sus2", m_semiTones = {_M_elems = "\000\002\a\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c104 "sus4", m_semiTones = {_M_elems = "\000\005\a\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c109 "aug", m_semiTones = {_M_elems = "\000\004\b\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c10d "augsus4", m_semiTones = {_M_elems = "\000\005\b\377\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c115 "tri", m_semiTones = {_M_elems = "\000\003\006\t\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c119 "6", m_semiTones = {_M_elems = "\000\004\a\t\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c11b "6sus4", m_semiTones = {_M_elems = "\000\005\a\t\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c121 "6add9", m_semiTones = {_M_elems = "\000\004\a\t\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c127 "m6", m_semiTones = {_M_elems = "\000\003\a\t\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c12a "m6add9", m_semiTones = {_M_elems = "\000\003\a\t\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c131 "7", m_semiTones = {_M_elems = "\000\004\a\n\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c133 "7sus4", m_semiTones = {_M_elems = "\000\005\a\n\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c139 "7#5", m_semiTones = {_M_elems = "\000\004\b\n\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c13d "7b5", m_semiTones = {_M_elems = "\000\004\006\n\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c141 "7#9", m_semiTones = {_M_elems = "\000\004\a\n\017\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c145 "7b9", m_semiTones = {_M_elems = "\000\004\a\n\r\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c149 "7#5#9", m_semiTones = {_M_elems = "\000\004\b\n\017\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c14f "7#5b9", m_semiTones = {_M_elems = "\000\004\b\n\r\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c155 "7b5b9", m_semiTones = {_M_elems = "\000\004\006\n\r\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c15b "7add11", m_semiTones = {_M_elems = "\000\004\a\n\021\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c162 "7add13", m_semiTones = {_M_elems = "\000\004\a\n\025\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c169 "7#11", m_semiTones = {_M_elems = "\000\004\a\n\022\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c16e "Maj7", m_semiTones = {_M_elems = "\000\004\a\v\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c173 "Maj7b5", m_semiTones = {_M_elems = "\000\004\006\v\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c17a "Maj7#5", m_semiTones = {_M_elems = "\000\004\b\v\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c181 "Maj7#11", m_semiTones = {_M_elems = "\000\004\a\v\022\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c189 "Maj7add13", m_semiTones = {_M_elems = "\000\004\a\v\025\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c193 "m7", m_semiTones = {_M_elems = "\000\003\a\n\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c196 "m7b5", m_semiTones = {_M_elems = "\000\003\006\n\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c19b "m7b9", m_semiTones = {_M_elems = "\000\003\a\n\r\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1a0 "m7add11", m_semiTones = {_M_elems = "\000\003\a\n\021\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1a8 "m7add13", m_semiTones = {_M_elems = "\000\003\a\n\025\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1b0 "m-Maj7", m_semiTones = {_M_elems = "\000\003\a\v\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1b7 "m-Maj7add11", m_semiTones = {_M_elems = "\000\003\a\v\021\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1c3 "m-Maj7add13", m_semiTones = {_M_elems = "\000\003\a\v\025\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1cf "9", m_semiTones = {_M_elems = "\000\004\a\n\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1d1 "9sus4", m_semiTones = {_M_elems = "\000\005\a\n\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1d7 "add9", m_semiTones = {_M_elems = "\000\004\a\016\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1dc "9#5", m_semiTones = {_M_elems = "\000\004\b\n\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1e0 "9b5", m_semiTones = {_M_elems = "\000\004\006\n\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1e4 "9#11", m_semiTones = {_M_elems = "\000\004\a\n\016\022\377\000\000\000\000\000"}}, {m_name = 0x555555a6c1e9 "9b13", m_semiTones = {_M_elems = "\000\004\a\n\016\024\377\000\000\000\000\000"}}, {m_name = 0x555555a6c1ee "Maj9", m_semiTones = {_M_elems = "\000\004\a\v\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1f3 "Maj9sus4", m_semiTones = {_M_elems = "\000\005\a\v\017\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c1fc "Maj9#5", m_semiTones = {_M_elems = "\000\004\b\v\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c203 "Maj9#11", m_semiTones = {_M_elems = "\000\004\a\v\016\022\377\000\000\000\000\000"}}, {m_name = 0x555555a6c20b "m9", m_semiTones = {_M_elems = "\000\003\a\n\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c20e "madd9", m_semiTones = {_M_elems = "\000\003\a\016\377\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c214 "m9b5", m_semiTones = {_M_elems = "\000\003\006\n\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c219 "m9-Maj7", m_semiTones = {_M_elems = "\000\003\a\v\016\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c221 "11", m_semiTones = {_M_elems = "\000\004\a\n\016\021\377\000\000\000\000\000"}}, {m_name = 0x555555a6c224 "11b9", m_semiTones = {_M_elems = "\000\004\a\n\r\021\377\000\000\000\000\000"}}, {m_name = 0x555555a6c229 "Maj11", m_semiTones = {_M_elems = "\000\004\a\v\016\021\377\000\000\000\000\000"}}, {m_name = 0x555555a6c22f "m11", m_semiTones = {_M_elems = "\000\003\a\n\016\021\377\000\000\000\000\000"}}, {m_name = 0x555555a6c233 "m-Maj11", m_semiTones = {_M_elems = "\000\003\a\v\016\021\377\000\000\000\000\000"}}, {m_name = 0x555555a6c23b "13", m_semiTones = {_M_elems = "\000\004\a\n\016\025\377\000\000\000\000\000"}}, {m_name = 0x555555a6c23e "13#9", m_semiTones = {_M_elems = "\000\004\a\n\017\025\377\000\000\000\000\000"}}, {m_name = 0x555555a6c243 "13b9", m_semiTones = {_M_elems = "\000\004\a\n\r\025\377\000\000\000\000\000"}}, {m_name = 0x555555a6c248 "13b5b9", m_semiTones = {_M_elems = "\000\004\006\n\r\025\377\000\000\000\000\000"}}, {m_name = 0x555555a6c24f "Maj13", m_semiTones = {_M_elems = "\000\004\a\v\016\025\377\000\000\000\000\000"}}, {m_name = 0x555555a6c255 "m13", m_semiTones = {_M_elems = "\000\003\a\n\016\025\377\000\000\000\000\000"}}, {m_name = 0x555555a6c259 "m-Maj13",--Type <RET> for more, q to quit, c to continue without paging--
 m_semiTones = {_M_elems = "\000\003\a\v\016\025\377\000\000\000\000\000"}}, {m_name = 0x555555a6c0e7 "Major", m_semiTones = {_M_elems = "\000\002\004\005\a\t\v\377\000\000\000\000"}}, {m_name = 0x555555a6c261 "Harmonic minor", m_semiTones = {_M_elems = "\000\002\003\005\a\b\v\377\000\000\000\000"}}, {m_name = 0x555555a6c270 "Melodic minor", m_semiTones = {_M_elems = "\000\002\003\005\a\t\v\377\000\000\000\000"}}, {m_name = 0x555555a6c27e "Whole tone", m_semiTones = {_M_elems = "\000\002\004\006\b\n\377\000\000\000\000\000"}}, {m_name = 0x555555a6c289 "Diminished", m_semiTones = {_M_elems = "\000\002\003\005\006\b\t\v\377\000\000\000"}}, {m_name = 0x555555a6c294 "Major pentatonic", m_semiTones = {_M_elems = "\000\002\004\a\t\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c2a5 "Minor pentatonic", m_semiTones = {_M_elems = "\000\003\005\a\n\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c2b6 "Jap in sen", m_semiTones = {_M_elems = "\000\001\005\a\n\377\000\000\000\000\000\000"}}, {m_name = 0x555555a6c2c1 "Major bebop", m_semiTones = {_M_elems = "\000\002\004\005\a\b\t\v\377\000\000\000"}}, {m_name = 0x555555a6c2cd "Dominant bebop", m_semiTones = {_M_elems = "\000\002\004\005\a\t\n\v\377\000\000\000"}}, {m_name = 0x555555a6c2dc "Blues", m_semiTones = {_M_elems = "\000\003\005\006\a\n\377\000\000\000\000\000"}}, {m_name = 0x555555a6c2e2 "Arabic", m_semiTones = {_M_elems = "\000\001\004\005\a\b\v\377\000\000\000\000"}}, {m_name = 0x555555a6c2e9 "Enigmatic", m_semiTones = {_M_elems = "\000\001\004\006\b\n\v\377\000\000\000\000"}}, {m_name = 0x555555a6c2f3 "Neopolitan", m_semiTones = {_M_elems = "\000\001\003\005\a\t\v\377\000\000\000\000"}}, {m_name = 0x555555a6c2fe "Neopolitan minor", m_semiTones = {_M_elems = "\000\001\003\005\a\b\v\377\000\000\000\000"}}, {m_name = 0x555555a6c30f "Hungarian minor", m_semiTones = {_M_elems = "\000\002\003\006\a\b\v\377\000\000\000\000"}}, {m_name = 0x555555a6c31f "Dorian", m_semiTones = {_M_elems = "\000\002\003\005\a\t\n\377\000\000\000\000"}}, {m_name = 0x555555a6c326 "Phrygian", m_semiTones = {_M_elems = "\000\001\003\005\a\b\n\377\000\000\000\000"}}, {m_name = 0x555555a6c32f "Lydian", m_semiTones = {_M_elems = "\000\002\004\006\a\t\v\377\000\000\000\000"}}, {m_name = 0x555555a6c336 "Mixolydian", m_semiTones = {_M_elems = "\000\002\004\005\a\t\n\377\000\000\000\000"}}, {m_name = 0x555555a6c341 "Aeolian", m_semiTones = {_M_elems = "\000\002\003\005\a\b\n\377\000\000\000\000"}}, {m_name = 0x555555a6c349 "Locrian", m_semiTones = {_M_elems = "\000\001\003\005\006\b\n\377\000\000\000\000"}}, {m_name = 0x555555a6c351 "Minor", m_semiTones = {_M_elems = "\000\002\003\005\a\b\n\377\000\000\000\000"}}, {m_name = 0x555555a6c357 "Chromatic", m_semiTones = {_M_elems = "\000\001\002\003\004\005\006\a\b\t\n\v\377"}}, {m_name = 0x555555a6c361 "Half-Whole Diminished", m_semiTones = {_M_elems = "\000\001\003\004\006\a\t\n\377\000\000\000"}}, {m_name = 0x555555a6c377 "5", m_semiTones = {_M_elems = "\000\a\377\000\000\000\000\000\000\000\000\000"}}, {m_name = 0x555555a6c379 "Phrygian dominant", m_semiTones = {_M_elems = "\000\001\004\005\a\b\n\377\000\000\000\000"}}, {m_name = 0x555555a6c38b "Persian", m_semiTones = {_M_elems = "\000\001\004\005\006\b\v\377\000\000\000\000"}}}}, m_chords = std::vector of length 95, capacity 128 = {{m_name = {d = 0x55555c7f02b0}, m_semiTones = {_M_elems = "\000\000\000\000\000\000\000\000\030\000\000\000"}, m_size = 1}, {m_name = {d = 0x55555c7f0b60}, m_semiTones = {_M_elems = "\000\004\a\000\000\000\000\000\000\000\000\000"}, m_size = 3}, {m_name = {d = 0x55555c7f0280}, m_semiTones = {_M_elems = "\000\004\006\000\000\000\000\000 {y\366\377"}, m_size = 3}, {m_name = {d = 0x55555c7f0b90}, m_semiTones = {_M_elems = "\000\003\a\000\000\000\000\000 {y\366\377"}, m_size = 3}, {m_name = {d = 0x55555c7f0bc0}, m_semiTones = {_M_elems = "\000\003\006\000\000\000\000\000 {y\366\377"}, m_size = 3}, {m_name = {d = 0x55555c7f0bf0}, m_semiTones = {_M_elems = "\000\002\a\000\000\000\000\000 {y\366\377"}, m_size = 3}, {m_name = {d = 0x55555c7f0c20}, m_semiTones = {_M_elems = "\000\005\a\000\000\000\000\000 {y\366\377"}, m_size = 3}, {m_name = {d = 0x55555c7f0c50}, m_semiTones = {_M_elems = "\000\004\b\000\000\000\000\000 {y\366\377"}, m_size = 3}, {m_name = {d = 0x55555c7f0e90}, m_semiTones = {_M_elems = "\000\005\b\000\000\000\000\000\000\000\000\000"}, m_size = 3}, {m_name = {d = 0x55555c7f0ec0}, m_semiTones = {_M_elems = "\000\003\006\t\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7f0ef0}, m_semiTones = {_M_elems = "\000\004\a\t\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7f0f20}, m_semiTones = {_M_elems = "\000\005\a\t\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7f0f50}, m_semiTones = {_M_elems = "\000\004\a\t\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f0f80}, m_semiTones = {_M_elems = "\000\003\a\t\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7f0fb0}, m_semiTones = {_M_elems = "\000\003\a\t\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f0fe0}, m_semiTones = {_M_elems = "\000\004\a\n\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7f1010}, m_semiTones = {_M_elems = "\000\005\a\nUU\000\000\340-@\\U"}, m_size = 4}, {m_name = {d = 0x55555c7f1040}, m_semiTones = {_M_elems = "\000\004\b\nUU\000\000P6nWU"}, m_size = 4}, {m_name = {d = 0x55555c7f1070}, m_semiTones = {_M_elems = "\000\004\006\nUU\000\000\2205@\\U"}, m_size = 4}, {m_name = {d = 0x55555c7f10a0}, m_semiTones = {_M_elems = "\000\004\a\n\017U\000\0000\210@\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f10d0}, m_semiTones = {_M_elems = "\000\004\a\n\rU\000\000\000\211@\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f1100}, m_semiTones = {_M_elems = "\000\004\b\n\017U\000\000p\362d\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f1130}, m_semiTones = {_M_elems = "\000\004\b\n\rU\000\000\260\364d\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f1160}, m_semiTones = {_M_elems = "\000\004\006\n\rU\000\000\360\366d\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f1190}, m_semiTones = {_M_elems = "\000\004\a\n\021U\000\000\200\370d\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f11c0}, m_semiTones = {_M_elems = "\000\004\a\n\025U\000\000\360\372d\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f11f0}, m_semiTones = {_M_elems = "\000\004\a\n\022U\000\000P\375d\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f1220}, m_semiTones = {_M_elems = "\000\004\a\vUU\000\0000\377d\\U"}, m_size = 4}, {m_name = {d = 0x55555c7f1250}, m_semiTones = {_M_elems = "\000\004\006\vUU\000\000\360\000e\\U"}, m_size = 4}, {m_name = {d = 0x55555c7f1280}, m_semiTones = {_M_elems = "\000\004\b\vUU\000\000\320\be\\U"}, m_size = 4}, {m_name = {d = 0x55555c7f12b0}, m_semiTones = {_M_elems = "\000\004\a\v\022U\000\000\240\ne\\U"}, m_size = 5}, {m_name = {d = 0x55555c7f12e0}, m_semiTones = {_M_elems = "\000\004\a\v\025U\000\000\020\fe\\U"}, m_size = 5}, {m_name = {d = 0x55555c7e5e50}, m_semiTones = {_M_elems = "\000\003\a\n\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7e5e80}, m_semiTones = {_M_elems = "\000\003\006\n\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7e5eb0}, m_semiTones = {_M_elems = "\000\003\a\n\r\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7e5ee0}, m_semiTones = {_M_elems = "\000\003\a\n\021\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7e5f10}, m_semiTones = {_M_elems = "\000\003\a\n\025\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7e5f40}, m_semiTones = {_M_elems = "\000\003\a\v\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7e5f70}, m_semiTones = {_M_elems = "\000\003\a\v\021\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1b30}, m_semiTones = {_M_elems = "\000\003\a\v\025\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1b70}, m_semiTones = {_M_elems = "\000\004\a\n\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1ba0}, m_semiTones = {_M_elems = "\000\005\a\n\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1bd0}, m_semiTones = {_M_elems = "\000\004\a\016\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7f1c00}, m_semiTones = {_M_elems = "\000\004\b\n\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1c30}, m_semiTones = {_M_elems = "\000\004\006\n\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1c60}, m_semiTones = {_M_elems = "\000\004\a\n\016\022\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1c90}, m_semiTones = {_M_elems = "\000\004\a\n\016\024\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1c--Type <RET> for more, q to quit, c to continue without paging--
c0}, m_semiTones = {_M_elems = "\000\004\a\v\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1cf0}, m_semiTones = {_M_elems = "\000\005\a\v\017\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1d30}, m_semiTones = {_M_elems = "\000\004\b\v\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1d60}, m_semiTones = {_M_elems = "\000\004\a\v\016\022\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1d90}, m_semiTones = {_M_elems = "\000\003\a\n\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1dc0}, m_semiTones = {_M_elems = "\000\003\a\016\000\000\000\000\000\000\000\000"}, m_size = 4}, {m_name = {d = 0x55555c7f1df0}, m_semiTones = {_M_elems = "\000\003\006\n\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1e20}, m_semiTones = {_M_elems = "\000\003\a\v\016\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1e50}, m_semiTones = {_M_elems = "\000\004\a\n\016\021\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1e80}, m_semiTones = {_M_elems = "\000\004\a\n\r\021\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1eb0}, m_semiTones = {_M_elems = "\000\004\a\v\016\021\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1ee0}, m_semiTones = {_M_elems = "\000\003\a\n\016\021\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1f10}, m_semiTones = {_M_elems = "\000\003\a\v\016\021\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1f40}, m_semiTones = {_M_elems = "\000\004\a\n\016\025\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1f70}, m_semiTones = {_M_elems = "\000\004\a\n\017\025\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1fa0}, m_semiTones = {_M_elems = "\000\004\a\n\r\025\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1fd0}, m_semiTones = {_M_elems = "\000\004\006\n\r\025\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f3010}, m_semiTones = {_M_elems = "\000\004\a\v\016\025\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1320}, m_semiTones = {_M_elems = "\000\003\a\n\016\025\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1350}, m_semiTones = {_M_elems = "\000\003\a\v\016\025\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1380}, m_semiTones = {_M_elems = "\000\002\004\005\a\t\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f13b0}, m_semiTones = {_M_elems = "\000\002\003\005\a\b\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f13f0}, m_semiTones = {_M_elems = "\000\002\003\005\a\t\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1430}, m_semiTones = {_M_elems = "\000\002\004\006\b\n\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f1470}, m_semiTones = {_M_elems = "\000\002\003\005\006\b\t\v\000\000\000\000"}, m_size = 8}, {m_name = {d = 0x55555c7e1130}, m_semiTones = {_M_elems = "\000\002\004\a\t\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f14b0}, m_semiTones = {_M_elems = "\000\003\005\a\n\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1500}, m_semiTones = {_M_elems = "\000\001\005\a\n\000\000\000\000\000\000\000"}, m_size = 5}, {m_name = {d = 0x55555c7f1540}, m_semiTones = {_M_elems = "\000\002\004\005\a\b\t\v\000\000\000\000"}, m_size = 8}, {m_name = {d = 0x55555c7f1580}, m_semiTones = {_M_elems = "\000\002\004\005\a\t\n\v\000\000\000\000"}, m_size = 8}, {m_name = {d = 0x55555c7f15c0}, m_semiTones = {_M_elems = "\000\003\005\006\a\n\000\000\000\000\000\000"}, m_size = 6}, {m_name = {d = 0x55555c7f15f0}, m_semiTones = {_M_elems = "\000\001\004\005\a\b\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1620}, m_semiTones = {_M_elems = "\000\001\004\006\b\n\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1660}, m_semiTones = {_M_elems = "\000\001\003\005\a\t\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f16a0}, m_semiTones = {_M_elems = "\000\001\003\005\a\b\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f16f0}, m_semiTones = {_M_elems = "\000\002\003\006\a\b\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1730}, m_semiTones = {_M_elems = "\000\002\003\005\a\t\n\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1760}, m_semiTones = {_M_elems = "\000\001\003\005\a\b\n\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f17a0}, m_semiTones = {_M_elems = "\000\002\004\006\a\t\v\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f17d0}, m_semiTones = {_M_elems = "\000\002\004\005\a\t\n\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1810}, m_semiTones = {_M_elems = "\000\002\003\005\a\b\n\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1840}, m_semiTones = {_M_elems = "\000\001\003\005\006\b\n\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f1870}, m_semiTones = {_M_elems = "\000\002\003\005\a\b\n\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f18a0}, m_semiTones = {_M_elems = "\000\001\002\003\004\005\006\a\b\t\n\v"}, m_size = 12}, {m_name = {d = 0x55555c7f18e0}, m_semiTones = {_M_elems = "\000\001\003\004\006\a\t\n\000\000\000\000"}, m_size = 8}, {m_name = {d = 0x55555c7f1930}, m_semiTones = {_M_elems = "\000\a\000\000\000\000\000\000\000\000\000\000"}, m_size = 2}, {m_name = {d = 0x55555c7f1960}, m_semiTones = {_M_elems = "\000\001\004\005\a\b\n\000\000\000\000\000"}, m_size = 7}, {m_name = {d = 0x55555c7f19b0}, m_semiTones = {_M_elems = "\000\001\004\005\006\b\v\000\000\000\000\000"}, m_size = 7}}}
#2  0x0000555555a26a2a in lmms::InstrumentTrack::playNote(lmms::NotePlayHandle*, std::array<float, 2ul>*) (this=0x7fff0c643e80, n=0x7ffff2a4f580, workingBuffer=0x7ffee82d1480)
    at /usr/local/src/lmms/src/tracks/InstrumentTrack.cpp:579
#3  0x000055555586b0ab in lmms::NotePlayHandle::play(std::array<float, 2ul>*) (this=0x7ffff2a4f580, _working_buffer=0x7ffee82d1480)
    at /usr/local/src/lmms/src/core/NotePlayHandle.cpp:263
        framesThisPeriod = 44
#4  0x0000555555879125 in lmms::PlayHandle::doProcessing() (this=0x7ffff2a4f580) at /usr/local/src/lmms/src/core/PlayHandle.cpp:59
#5  0x00005555557eb962 in lmms::ThreadableJob::process() (this=0x7ffff2a4f580) at /usr/local/src/lmms/include/ThreadableJob.h:77
        expected = lmms::ThreadableJob::ProcessingState::Queued
#6  0x00005555557eb316 in lmms::AudioEngineWorkerThread::JobQueue::run() (this=0x555555c0e380 <lmms::AudioEngineWorkerThread::globalJobQueue>)
    at /usr/local/src/lmms/src/core/AudioEngineWorkerThread.cpp:88
        job = 0x7ffff2a4f580
        i = 7
        processedJob = false
#7  0x00005555557eb651 in lmms::AudioEngineWorkerThread::run() (this=0x555556990180) at /usr/local/src/lmms/src/core/AudioEngineWorkerThread.cpp:178
        mmThreadGuard = {<No data fields>}
        m = {<QBasicMutex> = {d_ptr = {_q_value = std::atomic<QMutexData *> = { 0x1 }}}, <No data fields>}
#8  0x00007ffff64cbd43 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x00007ffff62a8044 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736003565248, 4991493368561989007, -288, 0, 140737488343984, 140735995174912, -4991652796624603761, -4991478701194938993}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#10 0x00007ffff632861c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

```
I’d add: yes, automate the chord type makes sense, at least to me. I love LMMS especially for this possibility to automate (automation curve or MIDI driven) alsmost everything!

**Comment by Veratil** [comment]
Which version are you running? Which OS?

Please make sure to use the default template next time so we don't have to ask these questions.
