### ISSUE TITLE
MIDI import crash

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#972]
win 32xp
Menu
  File | import (midi-notes)
  import in _existing_ project ->crash  
  import in _new_ clean project -ok

**Comment by Umcaruje** [comment]
Well I managed to hang LMMS by importing MIDI while a project was playing in the background:

Ubuntu 15.04 x64, master branch.
```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff6804062 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff68002f5 in QMutex::lockInternal() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x0000000000557dfa in Track::lock (this=0x7fffea9a2820) at /home/umcaruje/lmmsfork/lmms/include/Track.h:529
#4  0x000000000060ccf9 in InstrumentTrack::silenceAllNotes (this=0x7fffea9a2820, removeIPH=true) at /home/umcaruje/lmmsfork/lmms/src/tracks/InstrumentTrack.cpp:430
#5  0x000000000060ea4f in InstrumentTrack::loadInstrument (this=0x7fffea9a2820, _plugin_name=...) at /home/umcaruje/lmmsfork/lmms/src/tracks/InstrumentTrack.cpp:804
#6  0x00007fff9c23aa25 in smfMidiChannel::create (this=0x7fffffffa990, tc=0xca1d70, tn=...) at /home/umcaruje/lmmsfork/lmms/plugins/MidiImport/MidiImport.cpp:235
#7  0x00007fff9c238948 in MidiImport::readSMF (this=0x7fffea99af20, tc=0xca1d70) at /home/umcaruje/lmmsfork/lmms/plugins/MidiImport/MidiImport.cpp:427
#8  0x00007fff9c237b89 in MidiImport::tryImport (this=0x7fffea99af20, tc=0xca1d70) at /home/umcaruje/lmmsfork/lmms/plugins/MidiImport/MidiImport.cpp:129
#9  0x0000000000509884 in ImportFilter::import (_file_to_import=..., tc=0xca1d70) at /home/umcaruje/lmmsfork/lmms/src/core/ImportFilter.cpp:67
#10 0x0000000000549a05 in Song::importProject (this=0xca1d70) at /home/umcaruje/lmmsfork/lmms/src/core/Song.cpp:1172
#11 0x000000000062c320 in Song::qt_static_metacall (_o=0xca1d70, _c=QMetaObject::InvokeMetaMethod, _id=16, _a=0x7fffffffd500) at /home/umcaruje/lmmsfork/lmms/builddebug/src/moc_Song.cpp:120
#12 0x00007ffff69251ec in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff7082fd2 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007ffff7084b57 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#15 0x00007ffff69298e1 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#16 0x00007ffff7085022 in QAction::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007ffff70899bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007ffff70904d8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007ffff69101cd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007ffff6913a71 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff693f6ee in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x00007ffff3d98c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff3d98f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#24 0x00007ffff3d98fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff693f85e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#26 0x00007ffff7131c66 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#27 0x00007ffff690ed21 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#28 0x00007ffff690f085 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#29 0x00007ffff6914b09 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#30 0x00000000004d6c1f in main (argc=1, argv=0x7fffffffddb8) at /home/umcaruje/lmmsfork/lmms/src/core/main.cpp:677
```

Not sure if its the same case that @musikBear had though.
